using System.Collections.Generic;

namespace Cave.Domain
{
    public static class ArbitratedDomainRuntimeCommitVerification
    {
        public static bool TryRunAll(out string failure)
        {
            DomainConflictContestKey conflictKey=Key("C");
            CrossDomainArbitrationResult uncontested=DomainConflictArbitrator.Arbitrate(Read(Participant("A",Plan(Entry("X",0f,2f)),DomainConflictEvidenceSet.Empty)));
            ArbitratedDomainCommitPlan uncontestedPlan=ArbitratedDomainCommitPlanBuilder.Build(uncontested); Accessor singleAccessor=new Accessor();Target singleTarget=new Target(Snapshot(0f));singleAccessor.Add("X",singleTarget);ArbitratedDomainRuntimeCommitResult uncontestedCommit=new ArbitratedDomainRuntimeCommitter().Commit(uncontestedPlan,singleAccessor);

            CrossDomainArbitrationResult consensus=DomainConflictArbitrator.Arbitrate(Read(Participant("A",Plan(Entry("X",0f,2f)),DomainConflictEvidenceSet.Empty),Participant("B",Plan(Entry("X",0f,2f)),DomainConflictEvidenceSet.Empty)));ArbitratedDomainCommitPlan consensusPlan=ArbitratedDomainCommitPlanBuilder.Build(consensus);Accessor consensusAccessor=new Accessor();Target consensusTarget=new Target(Snapshot(0f));consensusAccessor.Add("X",consensusTarget);ArbitratedDomainRuntimeCommitResult consensusCommit=new ArbitratedDomainRuntimeCommitter().Commit(consensusPlan,consensusAccessor);

            CrossDomainArbitrationResult selected=DomainConflictArbitrator.Arbitrate(Read(Participant("A",Plan(Entry("C",0f,2f)),Evidence("A",conflictKey,true,3,0)),Participant("B",Plan(Entry("C",0f,1f)),Evidence("B",conflictKey,true,2,99))));ArbitratedDomainCommitPlan selectedPlan=ArbitratedDomainCommitPlanBuilder.Build(selected);Accessor selectedAccessor=new Accessor();Target selectedTarget=new Target(Snapshot(0f));selectedAccessor.Add("C",selectedTarget);ArbitratedDomainRuntimeCommitResult selectedCommit=new ArbitratedDomainRuntimeCommitter().Commit(selectedPlan,selectedAccessor);

            CrossDomainArbitrationResult deferred=DomainConflictArbitrator.Arbitrate(Read(Participant("A",Plan(Entry("D",0f,2f)),Evidence("A",Key("D"),true,1,1)),Participant("B",Plan(Entry("D",0f,-2f)),Evidence("B",Key("D"),true,1,1))));ArbitratedDomainCommitPlan deferredPlan=ArbitratedDomainCommitPlanBuilder.Build(deferred);Accessor deferredAccessor=new Accessor();Target deferredTarget=new Target(Snapshot(0f));deferredAccessor.Add("D",deferredTarget);ArbitratedDomainRuntimeCommitResult deferredCommit=new ArbitratedDomainRuntimeCommitter().Commit(deferredPlan,deferredAccessor);

            DomainConflictContestKey c=Key("C"),d=Key("D");CrossDomainArbitrationResult mixed=DomainConflictArbitrator.Arbitrate(Read(Participant("A",Plan(Entry("A",0f,2f),Entry("B",0f,2f),Entry("C",0f,2f),Entry("D",0f,2f)),EvidenceMany("A",c,true,3,0,d,true,1,1)),Participant("B",Plan(Entry("B",0f,2f),Entry("C",0f,1f),Entry("D",0f,-2f)),EvidenceMany("B",c,true,2,99,d,true,1,1))));ArbitratedDomainCommitPlan mixedPlan=ArbitratedDomainCommitPlanBuilder.Build(mixed);Accessor mixedAccessor=new Accessor();Target a=new Target(Snapshot(0f));Target b=new Target(Snapshot(0f));Target cc=new Target(Snapshot(0f));cc.Support=false;Target dd=new Target(Snapshot(0f));mixedAccessor.Add("A",a);mixedAccessor.Add("B",b);mixedAccessor.Add("C",cc);mixedAccessor.Add("D",dd);ArbitratedDomainRuntimeCommitResult mixedCommit=new ArbitratedDomainRuntimeCommitter().Commit(mixedPlan,mixedAccessor);

            CrossDomainArbitrationResult baselineMismatch=DomainConflictArbitrator.Arbitrate(Read(Participant("A",Plan(Entry("M",0f,2f)),DomainConflictEvidenceSet.Empty),Participant("B",Plan(Entry("M",1f,-2f)),DomainConflictEvidenceSet.Empty)));
            ArbitratedDomainCommitPlan nullPlan=ArbitratedDomainCommitPlanBuilder.Build(null);ArbitratedDomainCommitPlan invalidPlan=ArbitratedDomainCommitPlanBuilder.Build(baselineMismatch);
            CrossDomainArbitrationResult malformed=new CrossDomainArbitrationResult(uncontested.Participants,uncontested.Outcomes,Empty<CrossDomainAuthoritativeWrite>(),CrossDomainArbitrationRejectionReason.None);ArbitratedDomainCommitPlan malformedPlan=ArbitratedDomainCommitPlanBuilder.Build(malformed);
            List<CrossDomainAuthoritativeWrite> duplicateWrites=new List<CrossDomainAuthoritativeWrite>{uncontested.AuthoritativeWrites[0],uncontested.AuthoritativeWrites[0]};CrossDomainArbitrationResult duplicate=new CrossDomainArbitrationResult(uncontested.Participants,uncontested.Outcomes,duplicateWrites.AsReadOnly(),CrossDomainArbitrationRejectionReason.None);ArbitratedDomainCommitPlan duplicatePlan=ArbitratedDomainCommitPlanBuilder.Build(duplicate);
            List<CrossDomainAuthoritativeWrite> shuffledWrites=new List<CrossDomainAuthoritativeWrite>(mixed.AuthoritativeWrites);shuffledWrites.Reverse();CrossDomainArbitrationResult shuffled=new CrossDomainArbitrationResult(mixed.Participants,mixed.Outcomes,shuffledWrites.AsReadOnly(),CrossDomainArbitrationRejectionReason.None);ArbitratedDomainCommitPlan shuffledPlan=ArbitratedDomainCommitPlanBuilder.Build(shuffled);
            DomainConflictOutcome deferredOutcome=deferred.Outcomes[0];CrossDomainAuthoritativeWrite illegalDeferred=new CrossDomainAuthoritativeWrite(deferredOutcome,deferredOutcome.Candidates[0].Entry,Read("A"));CrossDomainArbitrationResult injectedDeferred=new CrossDomainArbitrationResult(deferred.Participants,deferred.Outcomes,Read(illegalDeferred),CrossDomainArbitrationRejectionReason.None);ArbitratedDomainCommitPlan injectedDeferredPlan=ArbitratedDomainCommitPlanBuilder.Build(injectedDeferred);
            DomainConflictOutcome originalOutcome=uncontested.Outcomes[0];DomainConflictCandidate originalCandidate=originalOutcome.SelectedCandidate;DomainCommitEntry forgedBefore=Entry("X",1f,2f);DomainConflictTrace forgedBaselineTrace=new DomainConflictTrace(Key("X"),Snapshot(1f),Read(originalCandidate));DomainConflictOutcome forgedBaselineOutcome=new DomainConflictOutcome(Key("X"),DomainConflictOutcomeKind.Uncontested,Read(originalCandidate),originalCandidate,forgedBaselineTrace);CrossDomainArbitrationResult forgedBaseline=new CrossDomainArbitrationResult(uncontested.Participants,Read(forgedBaselineOutcome),Read(new CrossDomainAuthoritativeWrite(forgedBaselineOutcome,originalCandidate.Entry,Read("A"))),CrossDomainArbitrationRejectionReason.None);ArbitratedDomainCommitPlan forgedBaselinePlan=ArbitratedDomainCommitPlanBuilder.Build(forgedBaseline);
            CrossDomainAuthoritativeWrite forgedAfterWrite=new CrossDomainAuthoritativeWrite(originalOutcome,Entry("X",0f,1f),Read("A"));CrossDomainArbitrationResult forgedAfter=new CrossDomainArbitrationResult(uncontested.Participants,uncontested.Outcomes,Read(forgedAfterWrite),CrossDomainArbitrationRejectionReason.None);ArbitratedDomainCommitPlan forgedAfterPlan=ArbitratedDomainCommitPlanBuilder.Build(forgedAfter);
            DomainConflictCandidate absentCandidate=new DomainConflictCandidate(uncontested.Participants[0],forgedBefore);DomainConflictOutcome absentLineageOutcome=new DomainConflictOutcome(Key("X"),DomainConflictOutcomeKind.Uncontested,Read(absentCandidate),absentCandidate,null);CrossDomainArbitrationResult absentLineage=new CrossDomainArbitrationResult(uncontested.Participants,Read(absentLineageOutcome),Empty<CrossDomainAuthoritativeWrite>(),CrossDomainArbitrationRejectionReason.None);ArbitratedDomainCommitPlan absentLineagePlan=ArbitratedDomainCommitPlanBuilder.Build(absentLineage);
            DomainCommitPlan invalidSourcePlan=new DomainCommitPlan(null,Read(Entry("X",0f,2f)),DomainCommitPlanRejectionReason.None);DomainConflictParticipant invalidParticipant=new DomainConflictParticipant("A",invalidSourcePlan,DomainComposition.Empty,null,DomainConflictEvidenceSet.Empty,"test");CrossDomainArbitrationResult invalidParticipantResult=new CrossDomainArbitrationResult(Read(invalidParticipant),uncontested.Outcomes,uncontested.AuthoritativeWrites,CrossDomainArbitrationRejectionReason.None);ArbitratedDomainCommitPlan invalidParticipantPlan=ArbitratedDomainCommitPlanBuilder.Build(invalidParticipantResult);
            Accessor staleAccessor=new Accessor();Target staleTarget=new Target(Snapshot(1f));staleAccessor.Add("X",staleTarget);ArbitratedDomainRuntimeCommitResult staleCommit=new ArbitratedDomainRuntimeCommitter().Commit(ArbitratedDomainCommitPlanBuilder.Build(uncontested),staleAccessor);
            ArbitratedDomainRuntimeCommitResult missingTargetCommit=new ArbitratedDomainRuntimeCommitter().Commit(ArbitratedDomainCommitPlanBuilder.Build(uncontested),new Accessor());
            ArbitratedDomainRuntimeCommitResult rejectedCommit=new ArbitratedDomainRuntimeCommitter().Commit(nullPlan,singleAccessor);

            bool pass=uncontestedPlan.IsCommittable&&uncontestedPlan.RuntimePlan.Entries.Count==1&&uncontestedCommit.Succeeded&&singleTarget.WriteCount==1&&Value(singleTarget.State)==2f
                &&consensusPlan.IsCommittable&&consensusPlan.RuntimePlan.Entries.Count==1&&consensusPlan.AuthoritativeWrites[0].SupportingParticipantIds.Count==2&&consensusCommit.Succeeded&&consensusTarget.WriteCount==1
                &&selectedPlan.IsCommittable&&selectedPlan.AuthoritativeWrites.Count==1&&selectedPlan.AuthoritativeWrites[0].Outcome.Kind==DomainConflictOutcomeKind.SelectedBySpecificity&&selectedCommit.Succeeded&&Value(selectedTarget.State)==2f
                &&deferredPlan.IsCommittable&&deferredPlan.RuntimePlan.Entries.Count==0&&deferredCommit.Succeeded&&deferredTarget.WriteCount==0&&Value(deferredTarget.State)==0f
                &&mixedPlan.IsCommittable&&mixedPlan.RuntimePlan.Entries.Count==3&&mixedCommit.RejectionReason==ArbitratedRuntimeCommitRejectionReason.None&&mixedCommit.RuntimeResult.RejectionReason==DomainCommitRejectionReason.UnsupportedPhenomenon&&a.WriteCount==0&&b.WriteCount==0&&cc.WriteCount==0&&dd.WriteCount==0
                &&shuffledPlan.IsCommittable&&shuffledPlan.RuntimePlan.Entries.Count==mixedPlan.RuntimePlan.Entries.Count&&shuffledPlan.RuntimePlan.Entries[0].CarrierId.Equals(mixedPlan.RuntimePlan.Entries[0].CarrierId)
                &&!nullPlan.IsCommittable&&nullPlan.RejectionReason==ArbitratedDomainCommitPlanRejectionReason.ArbitrationResultRequired&&!invalidPlan.IsCommittable&&invalidPlan.RejectionReason==ArbitratedDomainCommitPlanRejectionReason.InvalidConflict&&!malformedPlan.IsCommittable&&!duplicatePlan.IsCommittable&&duplicatePlan.RejectionReason==ArbitratedDomainCommitPlanRejectionReason.DuplicateSelectedKey&&!injectedDeferredPlan.IsCommittable&&injectedDeferredPlan.RejectionReason==ArbitratedDomainCommitPlanRejectionReason.BaselineDeferredIncluded
                &&!forgedBaselinePlan.IsCommittable&&forgedBaselinePlan.RejectionReason==ArbitratedDomainCommitPlanRejectionReason.SnapshotMismatch&&!forgedAfterPlan.IsCommittable&&!absentLineagePlan.IsCommittable&&absentLineagePlan.RejectionReason==ArbitratedDomainCommitPlanRejectionReason.MissingSelectedLineage&&!invalidParticipantPlan.IsCommittable&&invalidParticipantPlan.RejectionReason==ArbitratedDomainCommitPlanRejectionReason.InvalidParticipant
                &&!staleCommit.Succeeded&&staleCommit.RuntimeResult.RejectionReason==DomainCommitRejectionReason.RuntimeStateStale&&staleTarget.WriteCount==0&&!missingTargetCommit.Succeeded&&missingTargetCommit.RuntimeResult.RejectionReason==DomainCommitRejectionReason.MissingRuntimeTarget&&!rejectedCommit.Succeeded&&rejectedCommit.RejectionReason==ArbitratedRuntimeCommitRejectionReason.ArbitratedPlanNotCommittable;
            failure=pass?null:"Arbitrated runtime commit verification failed.";return pass;
        }
        private static DomainConflictParticipant Participant(string id,DomainCommitPlan plan,DomainConflictEvidenceSet evidence){return new DomainConflictParticipant(id,plan,DomainComposition.Empty,null,evidence,"test");}
        private static DomainConflictEvidenceSet Evidence(string id,DomainConflictContestKey key,bool jurisdiction,int specificity,int authority){return new DomainConflictEvidenceSet(Read(new DomainJurisdictionEvidence(id,key,jurisdiction,"test")),Read(new DomainSpecificityEvidence(id,key,specificity,"test")),Read(new DomainConflictAuthorityEvidence(id,key,authority,"test")));}
        private static DomainConflictEvidenceSet EvidenceMany(string id,DomainConflictContestKey first,bool firstJurisdiction,int firstSpecificity,int firstAuthority,DomainConflictContestKey second,bool secondJurisdiction,int secondSpecificity,int secondAuthority){return new DomainConflictEvidenceSet(Read(new DomainJurisdictionEvidence(id,first,firstJurisdiction,"test"),new DomainJurisdictionEvidence(id,second,secondJurisdiction,"test")),Read(new DomainSpecificityEvidence(id,first,firstSpecificity,"test"),new DomainSpecificityEvidence(id,second,secondSpecificity,"test")),Read(new DomainConflictAuthorityEvidence(id,first,firstAuthority,"test"),new DomainConflictAuthorityEvidence(id,second,secondAuthority,"test")));}
        private static DomainConflictContestKey Key(string carrier){return new DomainConflictContestKey(new PhenomenonCarrierId(carrier),LawPhenomenon.Heat);}
        private static DomainCommitEntry Entry(string carrier,float before,float after){return new DomainCommitEntry(new PhenomenonCarrierId(carrier),LawPhenomenon.Heat,Snapshot(before),Snapshot(after),Read(new DomainTransitionSequenceId(1)));}
        private static DomainCommitPlan Plan(params DomainCommitEntry[] entries){List<NormalizedSemanticTransition> g2=new List<NormalizedSemanticTransition>();for(int i=0;i<entries.Length;i++)g2.Add(new NormalizedSemanticTransition(new DomainTransitionSequenceId(i+1),DomainOrchestrationGeneration.Generation2,new DomainTransitionSequenceId(0),entries[i].CarrierId,entries[i].Phenomenon,entries[i].ExpectedBefore,entries[i].FinalAfter,PhenomenonOperationKind.Add,1f,DomainTransitionOrigin.Catalysis,null,true));return DomainCommitPlanBuilder.Build(Bounded(g2.AsReadOnly()));}
        private static DomainBoundedOrchestrationResult Bounded(IReadOnlyList<NormalizedSemanticTransition> g2){NormalizedSemanticTransition seed=g2[0];UnaryDomainGenerationZeroResult zero=DomainGenerationZeroExecutor.Execute(new UnaryDomainOrchestrationRequest(DomainComposition.Empty,new LawExpressionContext(true,LawExpression.Projectile,false),seed.Phenomenon,PhenomenonOperationKind.Add,1f,new PhenomenonCarrierSnapshot(seed.CarrierId,seed.Phenomenon,seed.Before),DomainOrchestrationContextSet.Empty));UnaryDomainGenerationOneResult one=new UnaryDomainGenerationOneResult(zero,Empty<DomainLawOutcomeTrace>(),Empty<PropagationEvaluationResult>(),Empty<SynchronizationEvaluationResult>(),Empty<NormalizedSemanticTransition>(),Empty<ProposalCollision>(),DomainGenerationOneRejectionReason.None);DomainResolvedGenerationOneResult resolved=DomainResolvedGenerationOneBuilder.Resolve(one);DomainGenerationTwoResult two=new DomainGenerationTwoResult(resolved,Empty<CatalysisObservationTrace>(),Empty<CatalysisEvaluationResult>(),g2,Empty<ProposalCollision>(),DomainGenerationTwoRejectionReason.None);return new DomainBoundedOrchestrationResult(zero,null,resolved,two,DomainProposalCompositionIntegrator.ResolveGenerationTwo(two));}
        private static PhenomenonSemanticSnapshot Snapshot(float value){PhenomenonSemanticSnapshot snapshot;PhenomenonSemanticResult result;PhenomenonSemanticClassifier.TryCreateSnapshot(LawPhenomenon.Heat,value,out snapshot,out result);return snapshot;}private static float Value(PhenomenonSemanticSnapshot value){return value!=null?value.SemanticValue:float.NaN;}
        private static IReadOnlyList<T> Read<T>(params T[] values){return new List<T>(values).AsReadOnly();}private static IReadOnlyList<T> Empty<T>(){return new List<T>().AsReadOnly();}
        private sealed class Accessor:IDomainPhenomenonRuntimeAccessor{private readonly List<Binding> bindings=new List<Binding>();public void Add(string carrier,Target target){bindings.Add(new Binding(new PhenomenonCarrierId(carrier),target));}public bool TryResolve(PhenomenonCarrierId carrier,LawPhenomenon phenomenon,out IDomainPhenomenonRuntimeTarget target){for(int i=0;i<bindings.Count;i++)if(bindings[i].Carrier.Equals(carrier)&&phenomenon==LawPhenomenon.Heat){target=bindings[i].Target;return true;}target=null;return false;}private sealed class Binding{public Binding(PhenomenonCarrierId carrier,Target target){Carrier=carrier;Target=target;}public PhenomenonCarrierId Carrier;public Target Target;}}
        private sealed class Target:IDomainPhenomenonRuntimeTarget{public Target(PhenomenonSemanticSnapshot state){State=state;}public PhenomenonSemanticSnapshot State;public bool Support=true;public int WriteCount;public bool TryRead(out PhenomenonSemanticSnapshot snapshot){snapshot=State;return snapshot!=null;}public bool TryValidateWrite(PhenomenonSemanticSnapshot final,out DomainRuntimeTargetRejectionReason reason){reason=Support?DomainRuntimeTargetRejectionReason.None:DomainRuntimeTargetRejectionReason.UnsupportedPhenomenon;return Support;}public void Apply(PhenomenonSemanticSnapshot final){State=final;WriteCount++;}}
    }
}
