using System.Collections.Generic;
namespace Cave.Domain
{
    public enum DomainResolvedGenerationOneRejectionReason { None = 0, GenerationOneRequired = 1 }
    public sealed class DomainUnresolvedGenerationOneKey
    { public DomainUnresolvedGenerationOneKey(PhenomenonCarrierId id, LawPhenomenon phenomenon) { CarrierId=id; Phenomenon=phenomenon; } public PhenomenonCarrierId CarrierId { get; } public LawPhenomenon Phenomenon { get; } }
    public sealed class DomainAuthoritativeGenerationOneTransition
    { internal DomainAuthoritativeGenerationOneTransition(NormalizedSemanticTransition raw) { RawTransition=raw; } internal DomainAuthoritativeGenerationOneTransition(DomainComposedTransition composed) { ComposedTransition=composed; } public NormalizedSemanticTransition RawTransition { get; } public DomainComposedTransition ComposedTransition { get; } public bool IsComposed => ComposedTransition!=null; public DomainTransitionSequenceId SequenceId => IsComposed?ComposedTransition.SequenceId:RawTransition.SequenceId; public DomainOrchestrationGeneration Generation => DomainOrchestrationGeneration.Generation1; public PhenomenonCarrierId CarrierId => IsComposed?ComposedTransition.CarrierId:RawTransition.CarrierId; public LawPhenomenon Phenomenon => IsComposed?ComposedTransition.Phenomenon:RawTransition.Phenomenon; public PhenomenonSemanticSnapshot Before => IsComposed?ComposedTransition.Before:RawTransition.Before; public PhenomenonSemanticSnapshot After => IsComposed?ComposedTransition.After:RawTransition.After; }
    public sealed class DomainPostGenerationOneState
    { internal DomainPostGenerationOneState(PhenomenonCarrierId id, LawPhenomenon phenomenon, PhenomenonSemanticSnapshot snapshot, bool unresolved) { CarrierId=id;Phenomenon=phenomenon;Snapshot=snapshot;IsUnresolved=unresolved; } public PhenomenonCarrierId CarrierId { get; } public LawPhenomenon Phenomenon { get; } public PhenomenonSemanticSnapshot Snapshot { get; } public bool IsUnresolved { get; } }
    public sealed class DomainResolvedGenerationOneResult
    {
        internal DomainResolvedGenerationOneResult(UnaryDomainGenerationOneResult unary, TransferDomainGenerationOneResult transfer, IReadOnlyList<DomainProposalCompositionResult> compositions, IReadOnlyList<DomainComposedTransition> nodes, IReadOnlyList<DomainAuthoritativeGenerationOneTransition> transitions, IReadOnlyList<DomainPostGenerationOneState> states, IReadOnlyList<DomainUnresolvedGenerationOneKey> unresolved, int next, DomainResolvedGenerationOneRejectionReason rejection = DomainResolvedGenerationOneRejectionReason.None) { UnaryRaw=unary;TransferRaw=transfer;ResolutionPlan=unary!=null?unary.ResolutionPlan:transfer!=null?transfer.ResolutionPlan:null;CompositionResults=compositions;ComposedTransitions=nodes;AuthoritativeTransitions=transitions;PostGenerationOneStates=states;UnresolvedKeys=unresolved;NextTransitionId=new DomainTransitionSequenceId(next);RejectionReason=rejection; }
        public UnaryDomainGenerationOneResult UnaryRaw { get; } public TransferDomainGenerationOneResult TransferRaw { get; } public DomainResolutionPlan ResolutionPlan { get; } public IReadOnlyList<DomainProposalCompositionResult> CompositionResults { get; } public IReadOnlyList<DomainComposedTransition> ComposedTransitions { get; } public IReadOnlyList<DomainAuthoritativeGenerationOneTransition> AuthoritativeTransitions { get; } public IReadOnlyList<DomainPostGenerationOneState> PostGenerationOneStates { get; } public IReadOnlyList<DomainUnresolvedGenerationOneKey> UnresolvedKeys { get; } public DomainTransitionSequenceId NextTransitionId { get; } public DomainResolvedGenerationOneRejectionReason RejectionReason { get; } public bool Succeeded => RejectionReason == DomainResolvedGenerationOneRejectionReason.None;
        public bool TryGetPostGenerationOneState(PhenomenonCarrierId id, LawPhenomenon phenomenon, out DomainPostGenerationOneState state) { for(int i=0;i<PostGenerationOneStates.Count;i++)if(PostGenerationOneStates[i].CarrierId.Equals(id)&&PostGenerationOneStates[i].Phenomenon==phenomenon){state=PostGenerationOneStates[i];return true;}state=null;return false; }
    }
    public static class DomainResolvedGenerationOneBuilder
    {
        public static DomainResolvedGenerationOneResult Resolve(UnaryDomainGenerationOneResult raw) { return Build(raw,null); }
        public static DomainResolvedGenerationOneResult Resolve(TransferDomainGenerationOneResult raw) { return Build(null,raw); }
        private static DomainResolvedGenerationOneResult Build(UnaryDomainGenerationOneResult unary, TransferDomainGenerationOneResult transfer)
        {
            if ((unary == null && transfer == null) || (unary != null && transfer != null) || (unary != null ? !IsValid(unary) : !IsValid(transfer))) return Rejected(unary, transfer);
            IReadOnlyList<NormalizedSemanticTransition> rawTransitions=unary!=null?unary.Transitions:transfer.Transitions; IReadOnlyList<ProposalCollision> collisions=unary!=null?unary.ProposalCollisions:transfer.ProposalCollisions;
            List<ProposalCollision> ordered=new List<ProposalCollision>(collisions);ordered.Sort((a,b)=>Min(a).CompareTo(Min(b)));List<DomainProposalCompositionResult> results=new List<DomainProposalCompositionResult>();for(int i=0;i<ordered.Count;i++)results.Add(DomainProposalComposer.TryCompose(ordered[i],rawTransitions));
            int next=System.Math.Max(Max(rawTransitions),MaxGenerationZero(unary,transfer))+1;List<DomainComposedTransition> nodes=new List<DomainComposedTransition>();for(int i=0;i<results.Count;i++)if(results[i].Resolved)nodes.Add(new DomainComposedTransition(new DomainTransitionSequenceId(next++),results[i]));
            List<DomainAuthoritativeGenerationOneTransition> authoritative=new List<DomainAuthoritativeGenerationOneTransition>();for(int i=0;i<rawTransitions.Count;i++)if(rawTransitions[i].IsUnambiguous)authoritative.Add(new DomainAuthoritativeGenerationOneTransition(rawTransitions[i]));for(int i=0;i<nodes.Count;i++)authoritative.Add(new DomainAuthoritativeGenerationOneTransition(nodes[i]));
            List<DomainUnresolvedGenerationOneKey> unresolved=new List<DomainUnresolvedGenerationOneKey>();for(int i=0;i<results.Count;i++)if(!results[i].Resolved)unresolved.Add(new DomainUnresolvedGenerationOneKey(results[i].CarrierId,results[i].Phenomenon));
            List<DomainPostGenerationOneState> states=States(unary,transfer,authoritative,unresolved);return new DomainResolvedGenerationOneResult(unary,transfer,results.AsReadOnly(),nodes.AsReadOnly(),authoritative.AsReadOnly(),states.AsReadOnly(),unresolved.AsReadOnly(),next);
        }
        private static DomainResolvedGenerationOneResult Rejected(UnaryDomainGenerationOneResult unary, TransferDomainGenerationOneResult transfer) { return new DomainResolvedGenerationOneResult(unary, transfer, Empty<DomainProposalCompositionResult>(), Empty<DomainComposedTransition>(), Empty<DomainAuthoritativeGenerationOneTransition>(), Empty<DomainPostGenerationOneState>(), Empty<DomainUnresolvedGenerationOneKey>(), -1, DomainResolvedGenerationOneRejectionReason.GenerationOneRequired); }
        private static bool IsValid(UnaryDomainGenerationOneResult raw) { return raw != null && raw.Succeeded && raw.GenerationZero != null && raw.GenerationZero.Succeeded && raw.GenerationZero.ResolutionPlan != null && raw.GenerationZero.PrimaryTransition != null && raw.ResolutionPlan != null && raw.Transitions != null && raw.ProposalCollisions != null && NoNulls(raw.Transitions) && NoNulls(raw.ProposalCollisions); }
        private static bool IsValid(TransferDomainGenerationOneResult raw) { return raw != null && raw.Succeeded && raw.GenerationZero != null && raw.GenerationZero.Succeeded && raw.GenerationZero.ResolutionPlan != null && raw.GenerationZero.SourceTransition != null && raw.GenerationZero.TargetTransition != null && raw.ResolutionPlan != null && raw.Transitions != null && raw.ProposalCollisions != null && NoNulls(raw.Transitions) && NoNulls(raw.ProposalCollisions); }
        private static bool NoNulls<T>(IReadOnlyList<T> values) where T : class { for (int i = 0; i < values.Count; i++) if (values[i] == null) return false; return true; }
        private static IReadOnlyList<T> Empty<T>() { return new List<T>().AsReadOnly(); }
        private static List<DomainPostGenerationOneState> States(UnaryDomainGenerationOneResult unary,TransferDomainGenerationOneResult transfer,IReadOnlyList<DomainAuthoritativeGenerationOneTransition> values,IReadOnlyList<DomainUnresolvedGenerationOneKey> unresolved){List<DomainPostGenerationOneState> states=new List<DomainPostGenerationOneState>();if(unary!=null)Put(states,unary.GenerationZero.PrimaryTransition);else{Put(states,transfer.GenerationZero.SourceTransition);Put(states,transfer.GenerationZero.TargetTransition);}for(int i=0;i<values.Count;i++)Put(states,values[i].CarrierId,values[i].Phenomenon,values[i].After);for(int i=0;i<unresolved.Count;i++)Put(states,unresolved[i].CarrierId,unresolved[i].Phenomenon,null,true);return states;}
        private static void Put(List<DomainPostGenerationOneState> states,NormalizedSemanticTransition t){Put(states,t.CarrierId,t.Phenomenon,t.After);}private static void Put(List<DomainPostGenerationOneState> states,PhenomenonCarrierId id,LawPhenomenon p,PhenomenonSemanticSnapshot s,bool unresolved=false){for(int i=0;i<states.Count;i++)if(states[i].CarrierId.Equals(id)&&states[i].Phenomenon==p){states[i]=new DomainPostGenerationOneState(id,p,s,unresolved);return;}states.Add(new DomainPostGenerationOneState(id,p,s,unresolved));}
        private static int Min(ProposalCollision c){int min=int.MaxValue;for(int i=0;i<c.InvolvedTransitionIds.Count;i++)if(c.InvolvedTransitionIds[i].Value<min)min=c.InvolvedTransitionIds[i].Value;return min;}private static int Max(IReadOnlyList<NormalizedSemanticTransition> ts){int max=-1;for(int i=0;i<ts.Count;i++)if(ts[i].SequenceId.Value>max)max=ts[i].SequenceId.Value;return max;}private static int MaxGenerationZero(UnaryDomainGenerationOneResult unary,TransferDomainGenerationOneResult transfer){return unary!=null?unary.GenerationZero.PrimaryTransition.SequenceId.Value:System.Math.Max(transfer.GenerationZero.SourceTransition.SequenceId.Value,transfer.GenerationZero.TargetTransition.SequenceId.Value);}
    }
}
