using System.Collections.Generic;

namespace Cave.Domain
{
    public static class DomainRuntimeCommitVerification
    {
        public static bool TryRunAll(out string failure)
        {
            DomainBoundedOrchestrationResult clean=Bounded(Empty<NormalizedSemanticTransition>(),Empty<ProposalCollision>(),Empty<NormalizedSemanticTransition>(),Empty<ProposalCollision>());
            DomainCommitPlan cleanPlan=DomainCommitPlanBuilder.Build(clean);
            Target cleanTarget=new Target(Snapshot(0f)); Accessor cleanAccessor=new Accessor();cleanAccessor.Add("A",LawPhenomenon.Heat,cleanTarget);DomainRuntimeCommitter cleanCommitter=new DomainRuntimeCommitter();DomainCommitResult committed=cleanCommitter.Commit(cleanPlan,cleanAccessor);DomainCommitResult replay=cleanCommitter.Commit(cleanPlan,cleanAccessor);

            NormalizedSemanticTransition g1=Transition(1,DomainOrchestrationGeneration.Generation1,"A",Snapshot(1f),Snapshot(2f),true); NormalizedSemanticTransition g2=Transition(2,DomainOrchestrationGeneration.Generation2,"A",Snapshot(2f),Snapshot(3f),true);
            DomainCommitPlan multiPlan=DomainCommitPlanBuilder.Build(Bounded(Read(g1),Empty<ProposalCollision>(),Read(g2),Empty<ProposalCollision>()));

            NormalizedSemanticTransition g2High=Transition(1,DomainOrchestrationGeneration.Generation2,"B",Snapshot(0f),Snapshot(2f),false); NormalizedSemanticTransition g2Low=Transition(2,DomainOrchestrationGeneration.Generation2,"B",Snapshot(0f),Snapshot(-2f),false); ProposalCollision opposed=Collision(DomainOrchestrationGeneration.Generation2,"B",g2High,g2Low);
            DomainCommitPlan unresolvedPlan=DomainCommitPlanBuilder.Build(Bounded(Empty<NormalizedSemanticTransition>(),Empty<ProposalCollision>(),Read(g2High,g2Low),Read(opposed)));
            DomainLaw catalysis=Law(LawTerritoryPrinciple.Catalysis); NormalizedSemanticTransition resolvedHighA=new NormalizedSemanticTransition(new DomainTransitionSequenceId(1),DomainOrchestrationGeneration.Generation2,new DomainTransitionSequenceId(1),new PhenomenonCarrierId("R"),LawPhenomenon.Heat,Snapshot(0f),Snapshot(2f),PhenomenonOperationKind.Add,2f,DomainTransitionOrigin.Catalysis,catalysis,false); NormalizedSemanticTransition resolvedHighB=new NormalizedSemanticTransition(new DomainTransitionSequenceId(2),DomainOrchestrationGeneration.Generation2,new DomainTransitionSequenceId(2),new PhenomenonCarrierId("R"),LawPhenomenon.Heat,Snapshot(0f),Snapshot(2f),PhenomenonOperationKind.Add,2f,DomainTransitionOrigin.Catalysis,catalysis,false); DomainCommitPlan resolvedCollisionPlan=DomainCommitPlanBuilder.Build(Bounded(Empty<NormalizedSemanticTransition>(),Empty<ProposalCollision>(),Read(resolvedHighA,resolvedHighB),Read(Collision(DomainOrchestrationGeneration.Generation2,"R",resolvedHighA,resolvedHighB))));

            DomainLaw propagation=Law(LawTerritoryPrinciple.Propagation);DomainLaw synchronization=Law(LawTerritoryPrinciple.Synchronization); NormalizedSemanticTransition noOpAdd=new NormalizedSemanticTransition(new DomainTransitionSequenceId(1),DomainOrchestrationGeneration.Generation1,new DomainTransitionSequenceId(0),new PhenomenonCarrierId("B"),LawPhenomenon.Heat,Snapshot(0f),Snapshot(2f),PhenomenonOperationKind.Add,2f,DomainTransitionOrigin.Propagation,propagation,false); NormalizedSemanticTransition noOpRemove=new NormalizedSemanticTransition(new DomainTransitionSequenceId(2),DomainOrchestrationGeneration.Generation1,new DomainTransitionSequenceId(0),new PhenomenonCarrierId("B"),LawPhenomenon.Heat,Snapshot(0f),Snapshot(-2f),PhenomenonOperationKind.Remove,2f,DomainTransitionOrigin.Synchronization,synchronization,false);
            DomainCommitPlan noOpPlan=DomainCommitPlanBuilder.Build(Bounded(Read(noOpAdd,noOpRemove),Read(Collision(DomainOrchestrationGeneration.Generation1,"B",noOpAdd,noOpRemove)),Empty<NormalizedSemanticTransition>(),Empty<ProposalCollision>()));

            Accessor staleAccessor=new Accessor();Target stale=new Target(Snapshot(1f));staleAccessor.Add("A",LawPhenomenon.Heat,stale);DomainCommitResult staleResult=new DomainRuntimeCommitter().Commit(cleanPlan,staleAccessor);
            DomainCommitResult missingResult=new DomainRuntimeCommitter().Commit(cleanPlan,new Accessor());
            Accessor unsupportedAccessor=new Accessor();Target unsupported=new Target(Snapshot(0f));unsupported.Support=false;unsupportedAccessor.Add("A",LawPhenomenon.Heat,unsupported);DomainCommitResult unsupportedResult=new DomainRuntimeCommitter().Commit(cleanPlan,unsupportedAccessor);
            Accessor lateAccessor=new Accessor();Target lateA=new Target(Snapshot(0f));Target lateB=new Target(Snapshot(0f));lateB.Support=false;lateAccessor.Add("A",LawPhenomenon.Heat,lateA);lateAccessor.Add("B",LawPhenomenon.Heat,lateB);DomainCommitResult lateResult=new DomainRuntimeCommitter().Commit(noOpPlan,lateAccessor);
            DomainCommitEntry massEntry=new DomainCommitEntry(new PhenomenonCarrierId("M"),LawPhenomenon.Mass,Snapshot(LawPhenomenon.Mass,1f),Snapshot(LawPhenomenon.Mass,1f),Read(new DomainTransitionSequenceId(0)));DomainCommitPlan massPlan=new DomainCommitPlan(null,Read(massEntry),DomainCommitPlanRejectionReason.None);Accessor massAccessor=new Accessor();Target massTarget=new Target(Snapshot(LawPhenomenon.Mass,1f));massTarget.Validation=DomainRuntimeTargetRejectionReason.MissingNaturalMassBaseline;massAccessor.Add("M",LawPhenomenon.Mass,massTarget);DomainCommitResult massResult=new DomainRuntimeCommitter().Commit(massPlan,massAccessor);

            bool pass=clean.Succeeded&&cleanPlan.IsCommittable&&cleanPlan.AffectedKeyCount==1&&cleanPlan.WriteCount==1&&cleanPlan.NoOpCount==0&&committed.Succeeded&&committed.CommittedEntryCount==1&&Value(cleanTarget.State)==1f&&cleanTarget.WriteCount==1&&!replay.Succeeded&&replay.RejectionReason==DomainCommitRejectionReason.PlanAlreadyCommitted
                &&multiPlan.IsCommittable&&multiPlan.Entries.Count==1&&Value(multiPlan.Entries[0].ExpectedBefore)==0f&&Value(multiPlan.Entries[0].FinalAfter)==3f&&multiPlan.Entries[0].CausalTransitionIds.Count==3&&multiPlan.Entries[0].CausalTransitionIds[0].Value==0&&multiPlan.Entries[0].CausalTransitionIds[2].Value==2
                &&!unresolvedPlan.IsCommittable&&unresolvedPlan.RejectionReason==DomainCommitPlanRejectionReason.UnresolvedCollision
                &&resolvedCollisionPlan.IsCommittable&&resolvedCollisionPlan.Source.HasRawProposalCollisions&&!resolvedCollisionPlan.Source.HasUnresolvedProposalCollisions
                &&noOpPlan.IsCommittable&&noOpPlan.Entries.Count==2&&noOpPlan.NoOpCount==1&&Find(noOpPlan,"B").IsNoOp
                &&!staleResult.Succeeded&&staleResult.RejectionReason==DomainCommitRejectionReason.RuntimeStateStale&&Value(stale.State)==1f
                &&!missingResult.Succeeded&&missingResult.RejectionReason==DomainCommitRejectionReason.MissingRuntimeTarget
                &&!unsupportedResult.Succeeded&&unsupportedResult.RejectionReason==DomainCommitRejectionReason.UnsupportedPhenomenon&&unsupported.WriteCount==0
                &&!lateResult.Succeeded&&lateResult.RejectionReason==DomainCommitRejectionReason.UnsupportedPhenomenon&&lateA.WriteCount==0
                &&!massResult.Succeeded&&massResult.TargetRejection==DomainRuntimeTargetRejectionReason.MissingNaturalMassBaseline&&massTarget.WriteCount==0;
            failure=pass?null:"Domain runtime commit verification failed.";return pass;
        }
        private static DomainBoundedOrchestrationResult Bounded(IReadOnlyList<NormalizedSemanticTransition> g1,IReadOnlyList<ProposalCollision> g1Collisions,IReadOnlyList<NormalizedSemanticTransition> g2,IReadOnlyList<ProposalCollision> g2Collisions){UnaryDomainGenerationZeroResult zero=DomainGenerationZeroExecutor.Execute(new UnaryDomainOrchestrationRequest(DomainComposition.Empty,new LawExpressionContext(true,LawExpression.Projectile,false),LawPhenomenon.Heat,PhenomenonOperationKind.Add,1f,Carrier("A",0f),DomainOrchestrationContextSet.Empty));UnaryDomainGenerationOneResult one=new UnaryDomainGenerationOneResult(zero,Empty<DomainLawOutcomeTrace>(),Empty<PropagationEvaluationResult>(),Empty<SynchronizationEvaluationResult>(),g1,g1Collisions,DomainGenerationOneRejectionReason.None);DomainResolvedGenerationOneResult resolved=DomainResolvedGenerationOneBuilder.Resolve(one);DomainGenerationTwoResult two=new DomainGenerationTwoResult(resolved,Empty<CatalysisObservationTrace>(),Empty<CatalysisEvaluationResult>(),g2,g2Collisions,DomainGenerationTwoRejectionReason.None);DomainProposalCompositionIntegrationResult final=DomainProposalCompositionIntegrator.ResolveGenerationTwo(two);return new DomainBoundedOrchestrationResult(zero,null,resolved,two,final);}
        private static DomainCommitEntry Find(DomainCommitPlan plan,string id){for(int i=0;i<plan.Entries.Count;i++)if(plan.Entries[i].CarrierId.Equals(new PhenomenonCarrierId(id)))return plan.Entries[i];return null;}
        private static DomainLaw Law(LawTerritoryPrinciple territory){DomainLaw law;LawValidationResult validation;DomainLaw.TryCreate(LawExpression.Projectile,LawPhenomenon.Heat,territory,out law,out validation);return law;}
        private static NormalizedSemanticTransition Transition(int id,DomainOrchestrationGeneration generation,string carrier,PhenomenonSemanticSnapshot before,PhenomenonSemanticSnapshot after,bool unambiguous){return new NormalizedSemanticTransition(new DomainTransitionSequenceId(id),generation,new DomainTransitionSequenceId(0),new PhenomenonCarrierId(carrier),LawPhenomenon.Heat,before,after,PhenomenonOperationKind.Add,1f,generation==DomainOrchestrationGeneration.Generation2?DomainTransitionOrigin.Catalysis:DomainTransitionOrigin.Propagation,null,unambiguous);}
        private static ProposalCollision Collision(DomainOrchestrationGeneration generation,string carrier,params NormalizedSemanticTransition[] values){List<DomainTransitionSequenceId> ids=new List<DomainTransitionSequenceId>();for(int i=0;i<values.Length;i++)ids.Add(values[i].SequenceId);return new ProposalCollision(new PhenomenonCarrierId(carrier),LawPhenomenon.Heat,generation,ids,new DomainLaw[0]);}
        private static PhenomenonCarrierSnapshot Carrier(string id,float value){return new PhenomenonCarrierSnapshot(new PhenomenonCarrierId(id),LawPhenomenon.Heat,Snapshot(value));}private static PhenomenonSemanticSnapshot Snapshot(float value){return Snapshot(LawPhenomenon.Heat,value);}private static PhenomenonSemanticSnapshot Snapshot(LawPhenomenon phenomenon,float value){PhenomenonSemanticSnapshot snapshot;PhenomenonSemanticResult result;PhenomenonSemanticClassifier.TryCreateSnapshot(phenomenon,value,out snapshot,out result);return snapshot;}private static float Value(PhenomenonSemanticSnapshot snapshot){return snapshot!=null?snapshot.SemanticValue:float.NaN;}private static IReadOnlyList<T> Read<T>(params T[] values){return new List<T>(values).AsReadOnly();}private static IReadOnlyList<T> Empty<T>(){return new List<T>().AsReadOnly();}
        private sealed class Accessor:IDomainPhenomenonRuntimeAccessor{private readonly List<Binding> bindings=new List<Binding>();public void Add(string id,LawPhenomenon phenomenon,Target target){bindings.Add(new Binding(new PhenomenonCarrierId(id),phenomenon,target));}public bool TryResolve(PhenomenonCarrierId id,LawPhenomenon phenomenon,out IDomainPhenomenonRuntimeTarget target){for(int i=0;i<bindings.Count;i++)if(bindings[i].Id.Equals(id)&&bindings[i].Phenomenon==phenomenon){target=bindings[i].Target;return true;}target=null;return false;}private sealed class Binding{public Binding(PhenomenonCarrierId id,LawPhenomenon phenomenon,Target target){Id=id;Phenomenon=phenomenon;Target=target;}public PhenomenonCarrierId Id;public LawPhenomenon Phenomenon;public Target Target;}}
        private sealed class Target:IDomainPhenomenonRuntimeTarget{public Target(PhenomenonSemanticSnapshot state){State=state;}public PhenomenonSemanticSnapshot State;public bool Support=true;public DomainRuntimeTargetRejectionReason Validation=DomainRuntimeTargetRejectionReason.None;public int WriteCount;public bool TryRead(out PhenomenonSemanticSnapshot snapshot){snapshot=State;return snapshot!=null;}public bool TryValidateWrite(PhenomenonSemanticSnapshot final,out DomainRuntimeTargetRejectionReason reason){reason=!Support?DomainRuntimeTargetRejectionReason.UnsupportedPhenomenon:Validation;return reason==DomainRuntimeTargetRejectionReason.None;}public void Apply(PhenomenonSemanticSnapshot final){State=final;WriteCount++;}}
    }
}
