using System.Collections.Generic;

namespace Cave.Domain
{
    public static class DomainProposalCompositionIntegrationVerification
    {
        public static bool TryRunAll(out string failure)
        {
            DomainLaw catalysis=Law(LawTerritoryPrinciple.Catalysis); DomainLaw propagation=Law(LawTerritoryPrinciple.Propagation); DomainLaw synchronization=Law(LawTerritoryPrinciple.Synchronization);
            PhenomenonSemanticSnapshot zero=Snapshot(0f); PhenomenonSemanticSnapshot one=Snapshot(1f); PhenomenonSemanticSnapshot two=Snapshot(2f); PhenomenonSemanticSnapshot three=Snapshot(3f); PhenomenonSemanticSnapshot low=Snapshot(-2f);
            DomainResolvedGenerationOneResult cleanG1=Resolved(Zero(),Read(GenerationOne(1,"A",propagation,zero,one,true)),Empty<ProposalCollision>());
            DomainProposalCompositionIntegrationResult clean=DomainProposalCompositionIntegrator.ResolveGenerationTwo(Raw(cleanG1,Read(GenerationTwo(2,1,"D",catalysis,zero,two,PhenomenonOperationKind.Add,2f,true)),Empty<ProposalCollision>()));

            NormalizedSemanticTransition highA=GenerationTwo(6,1,"D",catalysis,zero,two,PhenomenonOperationKind.Add,2f,false); NormalizedSemanticTransition highB=GenerationTwo(7,2,"D",catalysis,zero,two,PhenomenonOperationKind.Add,2f,false);
            ProposalCollision high=Collision("D",highA,highB); DomainGenerationTwoResult highRaw=Raw(cleanG1,Read(highA,highB),Read(high)); DomainProposalCompositionIntegrationResult highResult=DomainProposalCompositionIntegrator.ResolveGenerationTwo(highRaw); DomainProposalCompositionIntegrationResult highAgain=DomainProposalCompositionIntegrator.ResolveGenerationTwo(highRaw);

            NormalizedSemanticTransition highC=GenerationTwo(8,3,"D",catalysis,zero,two,PhenomenonOperationKind.Add,2f,false); DomainProposalCompositionIntegrationResult triple=DomainProposalCompositionIntegrator.ResolveGenerationTwo(Raw(cleanG1,Read(highA,highB,highC),Read(Collision("D",highA,highB,highC))));
            NormalizedSemanticTransition lowA=GenerationTwo(6,1,"L",catalysis,zero,low,PhenomenonOperationKind.Remove,2f,false); NormalizedSemanticTransition lowB=GenerationTwo(7,2,"L",catalysis,zero,low,PhenomenonOperationKind.Remove,2f,false); DomainProposalCompositionIntegrationResult lowResult=DomainProposalCompositionIntegrator.ResolveGenerationTwo(Raw(cleanG1,Read(lowA,lowB),Read(Collision("L",lowA,lowB))));
            NormalizedSemanticTransition opposedHigh=GenerationTwo(6,1,"O",catalysis,zero,two,PhenomenonOperationKind.Add,2f,false); NormalizedSemanticTransition opposedLow=GenerationTwo(7,2,"O",catalysis,zero,low,PhenomenonOperationKind.Remove,2f,false); DomainProposalCompositionIntegrationResult opposed=DomainProposalCompositionIntegrator.ResolveGenerationTwo(Raw(cleanG1,Read(opposedHigh,opposedLow),Read(Collision("O",opposedHigh,opposedLow))));
            NormalizedSemanticTransition mismatchBase=GenerationTwo(6,1,"M",catalysis,zero,two,PhenomenonOperationKind.Add,2f,false); NormalizedSemanticTransition mismatchHigh=GenerationTwo(7,2,"M",catalysis,zero,three,PhenomenonOperationKind.Add,3f,false); DomainProposalCompositionIntegrationResult mismatch=DomainProposalCompositionIntegrator.ResolveGenerationTwo(Raw(cleanG1,Read(mismatchBase,mismatchHigh),Read(Collision("M",mismatchBase,mismatchHigh))));

            NormalizedSemanticTransition multipleA=GenerationTwo(6,1,"B",catalysis,zero,two,PhenomenonOperationKind.Add,2f,false); NormalizedSemanticTransition multipleB=GenerationTwo(7,2,"B",catalysis,zero,two,PhenomenonOperationKind.Add,2f,false); NormalizedSemanticTransition multipleC=GenerationTwo(8,3,"C",catalysis,zero,two,PhenomenonOperationKind.Add,2f,false); NormalizedSemanticTransition multipleD=GenerationTwo(9,4,"C",catalysis,zero,two,PhenomenonOperationKind.Add,2f,false);
            DomainProposalCompositionIntegrationResult multiple=DomainProposalCompositionIntegrator.ResolveGenerationTwo(Raw(cleanG1,Read(multipleA,multipleB,multipleC,multipleD),Read(Collision("C",multipleC,multipleD),Collision("B",multipleA,multipleB))));
            NormalizedSemanticTransition partialHighA=GenerationTwo(6,1,"P",catalysis,zero,two,PhenomenonOperationKind.Add,2f,false); NormalizedSemanticTransition partialHighB=GenerationTwo(7,2,"P",catalysis,zero,two,PhenomenonOperationKind.Add,2f,false); NormalizedSemanticTransition partialLowA=GenerationTwo(8,3,"Q",catalysis,zero,two,PhenomenonOperationKind.Add,2f,false); NormalizedSemanticTransition partialLowB=GenerationTwo(9,4,"Q",catalysis,zero,low,PhenomenonOperationKind.Remove,2f,false);
            DomainProposalCompositionIntegrationResult partial=DomainProposalCompositionIntegrator.ResolveGenerationTwo(Raw(cleanG1,Read(partialHighA,partialHighB,partialLowA,partialLowB),Read(Collision("Q",partialLowA,partialLowB),Collision("P",partialHighA,partialHighB))));

            NormalizedSemanticTransition g1BadA=GenerationOne(1,"U",propagation,zero,one,false); NormalizedSemanticTransition g1BadB=GenerationOne(2,"U",synchronization,one,two,false); DomainResolvedGenerationOneResult unresolvedG1=Resolved(Zero(),Read(g1BadA,g1BadB),Read(CollisionGenerationOne("U",g1BadA,g1BadB))); DomainProposalCompositionIntegrationResult carried=DomainProposalCompositionIntegrator.ResolveGenerationTwo(Raw(unresolvedG1,Empty<NormalizedSemanticTransition>(),Empty<ProposalCollision>()));

            DomainGenerationTwoResult failed=new DomainGenerationTwoResult(cleanG1,Empty<CatalysisObservationTrace>(),Empty<CatalysisEvaluationResult>(),Empty<NormalizedSemanticTransition>(),Empty<ProposalCollision>(),DomainGenerationTwoRejectionReason.ResolvedGenerationOneRequired); DomainProposalCompositionIntegrationResult rejected=DomainProposalCompositionIntegrator.ResolveGenerationTwo(failed);

            DomainFinalSemanticState state; bool cleanState=clean.TryGetFinalState(new PhenomenonCarrierId("D"),LawPhenomenon.Heat,out state)&&!state.IsUnresolved&&Value(state.Snapshot)==2f;
            bool highState=highResult.TryGetFinalState(new PhenomenonCarrierId("D"),LawPhenomenon.Heat,out state)&&!state.IsUnresolved&&Value(state.Snapshot)==2f;
            bool opposedState=opposed.TryGetFinalState(new PhenomenonCarrierId("O"),LawPhenomenon.Heat,out state)&&state.IsUnresolved&&state.Snapshot==null;
            bool carriedState=carried.TryGetFinalState(new PhenomenonCarrierId("U"),LawPhenomenon.Heat,out state)&&state.IsUnresolved&&state.Snapshot==null;
            bool partialState=partial.TryGetFinalState(new PhenomenonCarrierId("P"),LawPhenomenon.Heat,out state)&&!state.IsUnresolved&&Value(state.Snapshot)==2f&&partial.TryGetFinalState(new PhenomenonCarrierId("Q"),LawPhenomenon.Heat,out state)&&state.IsUnresolved&&state.Snapshot==null;
            bool pass=clean.Succeeded&&clean.GenerationTwoCompositions.Count==0&&clean.GenerationTwoComposedTransitions.Count==0&&clean.AuthoritativeGenerationTwoTransitions.Count==1&&clean.AuthoritativeGenerationTwoTransitions[0].SequenceId.Value==2&&clean.FinalStates.Count>0&&clean.UnresolvedKeys.Count==0&&!clean.HasRawProposalCollisions&&!clean.HasUnresolvedProposalCollisions&&cleanState
                &&highResult.Succeeded&&highResult.GenerationTwoCompositions.Count==1&&highResult.GenerationTwoCompositions[0].Resolved&&highResult.GenerationTwoCompositions[0].Policy==ProposalCompositionPolicy.CatalysisCoalescence&&highResult.GenerationTwoComposedTransitions.Count==1&&highResult.GenerationTwoComposedTransitions[0].SequenceId.Value==8&&highResult.GenerationTwoComposedTransitions[0].IsTerminal&&highResult.GenerationTwoComposedTransitions[0].ParentTransitionIds.Count==2&&highResult.GenerationTwoComposedTransitions[0].OriginatingLaws.Count==1&&highResult.AuthoritativeGenerationTwoTransitions.Count==1&&highResult.AuthoritativeGenerationTwoTransitions[0].IsComposed&&highResult.NextTransitionId.Value==9&&highResult.HasRawProposalCollisions&&!highResult.HasUnresolvedProposalCollisions&&highState&&!highA.IsUnambiguous&&!highB.IsUnambiguous&&highRaw.Transitions[0]==highA&&highRaw.ProposalCollisions[0]==high&&highAgain.GenerationTwoComposedTransitions[0].SequenceId.Value==8
                &&triple.GenerationTwoComposedTransitions.Count==1&&triple.GenerationTwoComposedTransitions[0].ParentTransitionIds.Count==3&&triple.GenerationTwoComposedTransitions[0].After.Region==PhenomenonSemanticRegion.High&&lowResult.GenerationTwoComposedTransitions.Count==1&&lowResult.GenerationTwoComposedTransitions[0].After.Region==PhenomenonSemanticRegion.Low
                &&opposed.GenerationTwoComposedTransitions.Count==0&&opposed.GenerationTwoCompositions[0].Reason==ProposalCompositionReason.OpposedCatalysisDestinations&&opposed.UnresolvedKeys.Count==1&&opposed.HasRawProposalCollisions&&opposed.HasUnresolvedProposalCollisions&&opposedState
                &&mismatch.GenerationTwoComposedTransitions.Count==0&&mismatch.GenerationTwoCompositions[0].Reason==ProposalCompositionReason.CatalysisResultMismatch&&mismatch.UnresolvedKeys.Count==1
                &&multiple.GenerationTwoComposedTransitions.Count==2&&multiple.GenerationTwoComposedTransitions[0].SequenceId.Value==10&&multiple.GenerationTwoComposedTransitions[1].SequenceId.Value==11&&multiple.GenerationTwoComposedTransitions[0].CarrierId.Equals(new PhenomenonCarrierId("B"))&&multiple.GenerationTwoComposedTransitions[1].CarrierId.Equals(new PhenomenonCarrierId("C"))&&multiple.NextTransitionId.Value==12
                &&partial.GenerationTwoComposedTransitions.Count==1&&partial.UnresolvedKeys.Count==1&&partial.HasRawProposalCollisions&&partial.HasUnresolvedProposalCollisions&&partialState
                &&carried.UnresolvedKeys.Count==1&&carriedState&&carried.HasUnresolvedProposalCollisions&&!carried.GenerationTwoCompositions.Count.Equals(1)
                &&!rejected.Succeeded&&rejected.RejectionReason==DomainGenerationTwoCompositionRejectionReason.GenerationTwoRequired&&rejected.AuthoritativeGenerationTwoTransitions.Count==0&&!rejected.NextTransitionId.IsValid;
            failure=pass?null:"Generation-2 composition integration verification failed.";return pass;
        }
        private static DomainProposalCompositionIntegrationResult RawResult(DomainResolvedGenerationOneResult resolved,IReadOnlyList<NormalizedSemanticTransition> transitions,IReadOnlyList<ProposalCollision> collisions){return DomainProposalCompositionIntegrator.ResolveGenerationTwo(Raw(resolved,transitions,collisions));}
        private static DomainGenerationTwoResult Raw(DomainResolvedGenerationOneResult resolved,IReadOnlyList<NormalizedSemanticTransition> transitions,IReadOnlyList<ProposalCollision> collisions){return new DomainGenerationTwoResult(resolved,Empty<CatalysisObservationTrace>(),Empty<CatalysisEvaluationResult>(),transitions,collisions,DomainGenerationTwoRejectionReason.None);}
        private static DomainResolvedGenerationOneResult Resolved(UnaryDomainGenerationZeroResult zero,IReadOnlyList<NormalizedSemanticTransition> transitions,IReadOnlyList<ProposalCollision> collisions){return DomainResolvedGenerationOneBuilder.Resolve(new UnaryDomainGenerationOneResult(zero,Empty<DomainLawOutcomeTrace>(),Empty<PropagationEvaluationResult>(),Empty<SynchronizationEvaluationResult>(),transitions,collisions,DomainGenerationOneRejectionReason.None));}
        private static UnaryDomainGenerationZeroResult Zero(){return DomainGenerationZeroExecutor.Execute(new UnaryDomainOrchestrationRequest(DomainComposition.Empty,new LawExpressionContext(true,LawExpression.Projectile,false),LawPhenomenon.Heat,PhenomenonOperationKind.Add,0f,Carrier("A",0f),DomainOrchestrationContextSet.Empty));}
        private static DomainLaw Law(LawTerritoryPrinciple territory){DomainLaw law;LawValidationResult validation;DomainLaw.TryCreate(LawExpression.Projectile,LawPhenomenon.Heat,territory,out law,out validation);return law;}
        private static PhenomenonCarrierSnapshot Carrier(string id,float value){return new PhenomenonCarrierSnapshot(new PhenomenonCarrierId(id),LawPhenomenon.Heat,Snapshot(value));}
        private static PhenomenonSemanticSnapshot Snapshot(float value){PhenomenonSemanticSnapshot snapshot;PhenomenonSemanticResult result;PhenomenonSemanticClassifier.TryCreateSnapshot(LawPhenomenon.Heat,value,out snapshot,out result);return snapshot;}
        private static NormalizedSemanticTransition GenerationOne(int id,string carrier,DomainLaw law,PhenomenonSemanticSnapshot before,PhenomenonSemanticSnapshot after,bool unambiguous){return new NormalizedSemanticTransition(new DomainTransitionSequenceId(id),DomainOrchestrationGeneration.Generation1,new DomainTransitionSequenceId(0),new PhenomenonCarrierId(carrier),LawPhenomenon.Heat,before,after,PhenomenonOperationKind.Add,1f,law.TerritoryPrinciple==LawTerritoryPrinciple.Synchronization?DomainTransitionOrigin.Synchronization:DomainTransitionOrigin.Propagation,law,unambiguous);}
        private static NormalizedSemanticTransition GenerationTwo(int id,int parent,string carrier,DomainLaw law,PhenomenonSemanticSnapshot before,PhenomenonSemanticSnapshot after,PhenomenonOperationKind operation,float magnitude,bool unambiguous){return new NormalizedSemanticTransition(new DomainTransitionSequenceId(id),DomainOrchestrationGeneration.Generation2,new DomainTransitionSequenceId(parent),new PhenomenonCarrierId(carrier),LawPhenomenon.Heat,before,after,operation,magnitude,DomainTransitionOrigin.Catalysis,law,unambiguous);}
        private static ProposalCollision Collision(string carrier,params NormalizedSemanticTransition[] values){return CollisionFor(DomainOrchestrationGeneration.Generation2,carrier,values);}private static ProposalCollision CollisionGenerationOne(string carrier,params NormalizedSemanticTransition[] values){return CollisionFor(DomainOrchestrationGeneration.Generation1,carrier,values);}private static ProposalCollision CollisionFor(DomainOrchestrationGeneration generation,string carrier,NormalizedSemanticTransition[] values){List<DomainTransitionSequenceId> ids=new List<DomainTransitionSequenceId>();List<DomainLaw> laws=new List<DomainLaw>();for(int i=0;i<values.Length;i++){ids.Add(values[i].SequenceId);if(!laws.Contains(values[i].OriginatingLaw))laws.Add(values[i].OriginatingLaw);}return new ProposalCollision(new PhenomenonCarrierId(carrier),LawPhenomenon.Heat,generation,ids,laws);}
        private static float Value(PhenomenonSemanticSnapshot snapshot){return snapshot!=null?snapshot.SemanticValue:float.NaN;}private static IReadOnlyList<T> Read<T>(params T[] values){return new List<T>(values).AsReadOnly();}private static IReadOnlyList<T> Empty<T>(){return new List<T>().AsReadOnly();}
    }
}
