using Cave.Axioms.Mastery;
namespace Cave.Domain
{
 public enum DomainAuthoringRejectionReason { None, InvalidContext, DomainSeedRequired, InvalidLaw, DuplicateLaw, PhenomenonMasteryIncomplete, ExpressionMasteryIncomplete, InvalidComplexityCapacity, ComplexityCapacityExceeded }
 public sealed class DomainAuthoringContext { public DomainAuthoringContext(bool seed, PlayerMasteryEvidenceState mastery,float capacity,PlayerMasteryPolicy policy,DomainComplexityPolicy complexityPolicy){HasDomainSeed=seed;Mastery=mastery;ComplexityCapacity=capacity;MasteryPolicy=policy;ComplexityPolicy=complexityPolicy;} public bool HasDomainSeed{get;} public PlayerMasteryEvidenceState Mastery{get;} public float ComplexityCapacity{get;} public PlayerMasteryPolicy MasteryPolicy{get;} public DomainComplexityPolicy ComplexityPolicy{get;} }
 public sealed class DomainAuthoringEligibilityResult { internal DomainAuthoringEligibilityResult(bool ok,DomainAuthoringRejectionReason reason,DomainComposition current,DomainComposition proposed,DomainMasteryEligibilityResult mastery,DomainComplexityReport currentReport,DomainComplexityReport proposedReport,DomainAuthoringContext context){IsEligible=ok;RejectionReason=reason;Current=current;Proposed=proposed;Mastery=mastery;CurrentComplexity=currentReport;ProposedComplexity=proposedReport;Context=context;} public bool IsEligible{get;} public DomainAuthoringRejectionReason RejectionReason{get;} public DomainComposition Current{get;} public DomainComposition Proposed{get;} public DomainMasteryEligibilityResult Mastery{get;} public DomainComplexityReport CurrentComplexity{get;} public DomainComplexityReport ProposedComplexity{get;} public DomainAuthoringContext Context{get;} public float ComplexityRemaining=>ProposedComplexity==null?0f:Context.ComplexityCapacity-ProposedComplexity.TotalComplexity; public float ComplexityExcess=>ComplexityRemaining<0f?-ComplexityRemaining:0f; }
 public static class DomainAuthoringEligibility
 {
  public static DomainAuthoringEligibilityResult Evaluate(DomainComposition current,DomainLaw candidate,DomainAuthoringContext context){DomainComposition c=current??DomainComposition.Empty; if(context==null||context.MasteryPolicy==null||context.ComplexityPolicy==null)return R(false,DomainAuthoringRejectionReason.InvalidContext,c,null,null,context); var cr=DomainComplexityCalculator.Calculate(c,context.ComplexityPolicy); if(context.ComplexityCapacity<0f)return new DomainAuthoringEligibilityResult(false,DomainAuthoringRejectionReason.InvalidComplexityCapacity,c,null,null,cr,null,context); if(!context.HasDomainSeed)return new DomainAuthoringEligibilityResult(false,DomainAuthoringRejectionReason.DomainSeedRequired,c,null,null,cr,null,context); if(candidate==null||!DomainLaw.Validate(candidate.Expression,candidate.Phenomenon,candidate.TerritoryPrinciple).IsValid)return new DomainAuthoringEligibilityResult(false,DomainAuthoringRejectionReason.InvalidLaw,c,null,null,cr,null,context); if(c.Contains(candidate))return new DomainAuthoringEligibilityResult(false,DomainAuthoringRejectionReason.DuplicateLaw,c,c,null,cr,cr,context); var m=DomainMasteryEligibility.Evaluate(candidate,context.Mastery,context.MasteryPolicy); if(!m.IsEligible)return new DomainAuthoringEligibilityResult(false,m.Reason==DomainMasteryEligibilityReason.PhenomenonMasteryIncomplete?DomainAuthoringRejectionReason.PhenomenonMasteryIncomplete:DomainAuthoringRejectionReason.ExpressionMasteryIncomplete,c,null,m,cr,null,context); var add=DomainCompositionEditor.Add(c,candidate); var pr=DomainComplexityCalculator.Calculate(add.Resulting,context.ComplexityPolicy); return new DomainAuthoringEligibilityResult(pr.TotalComplexity<=context.ComplexityCapacity,pr.TotalComplexity<=context.ComplexityCapacity?DomainAuthoringRejectionReason.None:DomainAuthoringRejectionReason.ComplexityCapacityExceeded,c,add.Resulting,m,cr,pr,context);}
  private static DomainAuthoringEligibilityResult R(bool ok,DomainAuthoringRejectionReason r,DomainComposition c,DomainComposition p,DomainMasteryEligibilityResult m,DomainAuthoringContext x){return new DomainAuthoringEligibilityResult(ok,r,c,p,m,null,null,x);}
 }
}
