using System.Collections.Generic;
namespace Cave.Domain
{
 public enum DomainResolutionCausalPhase { IntentTransformation, RelationalResolution, PostResolutionObservation }
 public enum DomainResolutionRequiredContext { BaseIntentOnly, PropagationTopology, ConvergenceTopology, RelationshipGroupAndSnapshots, InterferenceParticipantsAndFocalTarget, ResolvedBeforeAfterTransition }
 public enum DomainResolutionOperationCompatibility { Supported, OperationUnsupported, NoDefinedInverse, RequiresPostResolutionState }
 public sealed class DomainResolutionIntent { public DomainResolutionIntent(DomainComposition c,LawExpressionContext x,LawPhenomenon p,PhenomenonOperationKind o,float m){Composition=c;ExpressionContext=x;Phenomenon=p;Operation=o;Magnitude=m;} public DomainComposition Composition{get;} public LawExpressionContext ExpressionContext{get;} public LawPhenomenon Phenomenon{get;} public PhenomenonOperationKind Operation{get;} public float Magnitude{get;} }
 public sealed class PlannedDomainLaw { internal PlannedDomainLaw(DomainLaw l,int i,bool e,LawEvaluationRejectionReason r,DomainResolutionCausalPhase p,DomainResolutionRequiredContext c,DomainResolutionOperationCompatibility o){CandidateLaw=l;CompositionIndex=i;SharedEligible=e;EligibilityReason=r;Phase=p;RequiredContext=c;OperationCompatibility=o;} public DomainLaw CandidateLaw{get;} public int CompositionIndex{get;} public bool SharedEligible{get;} public LawEvaluationRejectionReason EligibilityReason{get;} public DomainResolutionCausalPhase Phase{get;} public DomainResolutionRequiredContext RequiredContext{get;} public DomainResolutionOperationCompatibility OperationCompatibility{get;} public bool IsImmediatelyEvaluable=>SharedEligible&&OperationCompatibility==DomainResolutionOperationCompatibility.Supported; }
 public sealed class DomainResolutionPlan { internal DomainResolutionPlan(DomainResolutionIntent i,IReadOnlyList<PlannedDomainLaw> l){Intent=i;Laws=l;} public DomainResolutionIntent Intent{get;} public IReadOnlyList<PlannedDomainLaw> Laws{get;} public bool HasIntentTransformations=>Has(DomainResolutionCausalPhase.IntentTransformation); public bool HasRelationalCandidates=>Has(DomainResolutionCausalPhase.RelationalResolution); public bool HasPostResolutionObservers=>Has(DomainResolutionCausalPhase.PostResolutionObservation); bool Has(DomainResolutionCausalPhase p){foreach(var l in Laws)if(l.SharedEligible&&l.Phase==p)return true;return false;} }
 public static class DomainResolutionPlanner { public static DomainResolutionPlan Plan(DomainResolutionIntent i){var list=new List<PlannedDomainLaw>(); var c=i!=null&&i.Composition!=null?i.Composition:DomainComposition.Empty; for(int n=0;n<c.Count;n++){var l=c.OrderedLaws[n]; LawEvaluationRejectionReason r; bool e=DomainLawEvaluator.TryEvaluateEligibility(l,i==null?null:i.ExpressionContext,out r)&&l.Phenomenon==i.Phenomenon; if(e)r=LawEvaluationRejectionReason.None; else if(l.Phenomenon!=(i==null?default(LawPhenomenon):i.Phenomenon))r=LawEvaluationRejectionReason.PhenomenonMismatch; var p=l.TerritoryPrinciple==LawTerritoryPrinciple.Catalysis?DomainResolutionCausalPhase.PostResolutionObservation:(l.TerritoryPrinciple==LawTerritoryPrinciple.Reversal||l.TerritoryPrinciple==LawTerritoryPrinciple.Interference?DomainResolutionCausalPhase.IntentTransformation:DomainResolutionCausalPhase.RelationalResolution); var x=l.TerritoryPrinciple==LawTerritoryPrinciple.Reversal?DomainResolutionRequiredContext.BaseIntentOnly:l.TerritoryPrinciple==LawTerritoryPrinciple.Propagation?DomainResolutionRequiredContext.PropagationTopology:l.TerritoryPrinciple==LawTerritoryPrinciple.Accumulation?DomainResolutionRequiredContext.ConvergenceTopology:l.TerritoryPrinciple==LawTerritoryPrinciple.Synchronization?DomainResolutionRequiredContext.RelationshipGroupAndSnapshots:l.TerritoryPrinciple==LawTerritoryPrinciple.Interference?DomainResolutionRequiredContext.InterferenceParticipantsAndFocalTarget:DomainResolutionRequiredContext.ResolvedBeforeAfterTransition; var o=l.TerritoryPrinciple==LawTerritoryPrinciple.Catalysis?DomainResolutionOperationCompatibility.RequiresPostResolutionState:(i!=null&&i.Operation==PhenomenonOperationKind.Transfer?(l.TerritoryPrinciple==LawTerritoryPrinciple.Accumulation?DomainResolutionOperationCompatibility.Supported:l.TerritoryPrinciple==LawTerritoryPrinciple.Reversal?DomainResolutionOperationCompatibility.NoDefinedInverse:DomainResolutionOperationCompatibility.OperationUnsupported):DomainResolutionOperationCompatibility.Supported); list.Add(new PlannedDomainLaw(l,n,e,r,p,x,o));} return new DomainResolutionPlan(i,list.AsReadOnly());} }
}
