using System.Collections.Generic;

namespace Cave.Domain
{
    public enum DomainGenerationTwoRejectionReason { None = 0, ResolvedGenerationOneRequired = 1 }
    public enum CatalysisObservationBlockReason { None = 0, ContextUnavailable = 1, SourceTransitionAmbiguous = 2, PriorStateAmbiguous = 3, EvaluatorRejected = 4, SourceStateUnresolved = 5 }
    public sealed class CatalysisObserverBranchKey
    {
        public CatalysisObserverBranchKey(DomainLaw law, DomainTransitionSequenceId sourceTransitionId) { Law = law; SourceTransitionId = sourceTransitionId; }
        public DomainLaw Law { get; } public DomainTransitionSequenceId SourceTransitionId { get; }
        public bool Equals(CatalysisObserverBranchKey other) { return other != null && Equals(Law, other.Law) && SourceTransitionId.Equals(other.SourceTransitionId); }
    }
    public sealed class CatalysisRecipientObservationBlock
    { public CatalysisRecipientObservationBlock(PhenomenonCarrierId carrierId) { CarrierId = carrierId; Reason = CatalysisObservationBlockReason.PriorStateAmbiguous; } public PhenomenonCarrierId CarrierId { get; } public CatalysisObservationBlockReason Reason { get; } }
    public sealed class CatalysisObservationTrace
    {
        internal CatalysisObservationTrace(DomainLaw law, DomainTransitionSequenceId sourceId, PhenomenonCarrierId sourceCarrier, bool attempted, bool contextAvailable, bool triggered, CatalysisEvaluationRejectionReason? rejection, CatalysisObservationBlockReason block, int transitionCount, IReadOnlyList<CatalysisRecipientObservationBlock> recipientBlocks)
        { Law = law; SourceTransitionId = sourceId; SourceCarrierId = sourceCarrier; Attempted = attempted; ContextAvailable = contextAvailable; Triggered = triggered; EvaluationRejection = rejection; BlockReason = block; GeneratedTransitionCount = transitionCount; RecipientBlocks = recipientBlocks; }
        public DomainLaw Law { get; } public DomainTransitionSequenceId SourceTransitionId { get; } public PhenomenonCarrierId SourceCarrierId { get; }
        public bool Attempted { get; } public bool ContextAvailable { get; } public bool Triggered { get; } public CatalysisEvaluationRejectionReason? EvaluationRejection { get; } public CatalysisObservationBlockReason BlockReason { get; } public int GeneratedTransitionCount { get; } public IReadOnlyList<CatalysisRecipientObservationBlock> RecipientBlocks { get; }
    }
    public sealed class DomainGenerationTwoResult
    {
        internal DomainGenerationTwoResult(DomainResolvedGenerationOneResult resolved, IReadOnlyList<CatalysisObservationTrace> observations, IReadOnlyList<CatalysisEvaluationResult> evaluations, IReadOnlyList<NormalizedSemanticTransition> transitions, IReadOnlyList<ProposalCollision> collisions, DomainGenerationTwoRejectionReason rejection)
        { ResolvedGenerationOne = resolved; UnaryGenerationOne = resolved != null ? resolved.UnaryRaw : null; TransferGenerationOne = resolved != null ? resolved.TransferRaw : null; ResolutionPlan = resolved != null ? resolved.ResolutionPlan : null; Observations = observations; EvaluationResults = evaluations; Transitions = transitions; ProposalCollisions = collisions; RejectionReason = rejection; }
        public DomainResolvedGenerationOneResult ResolvedGenerationOne { get; } public UnaryDomainGenerationOneResult UnaryGenerationOne { get; } public TransferDomainGenerationOneResult TransferGenerationOne { get; } public DomainResolutionPlan ResolutionPlan { get; }
        public IReadOnlyList<CatalysisObservationTrace> Observations { get; } public IReadOnlyList<CatalysisEvaluationResult> EvaluationResults { get; } public IReadOnlyList<NormalizedSemanticTransition> Transitions { get; } public IReadOnlyList<ProposalCollision> ProposalCollisions { get; }
        public bool Succeeded => RejectionReason == DomainGenerationTwoRejectionReason.None; public bool Generation2Executed => true; public DomainGenerationTwoRejectionReason RejectionReason { get; }
    }

    public sealed class DomainBoundedOrchestrationResult
    {
        internal DomainBoundedOrchestrationResult(UnaryDomainGenerationZeroResult unaryZero, TransferDomainGenerationZeroResult transferZero, DomainResolvedGenerationOneResult resolvedOne, DomainGenerationTwoResult two, DomainProposalCompositionIntegrationResult finalResolution)
        { UnaryGenerationZero = unaryZero; TransferGenerationZero = transferZero; ResolvedGenerationOne = resolvedOne; UnaryGenerationOne = resolvedOne != null ? resolvedOne.UnaryRaw : null; TransferGenerationOne = resolvedOne != null ? resolvedOne.TransferRaw : null; GenerationTwo = two; FinalResolution = finalResolution; ResolutionPlan = two != null ? two.ResolutionPlan : resolvedOne != null ? resolvedOne.ResolutionPlan : unaryZero != null ? unaryZero.ResolutionPlan : transferZero != null ? transferZero.ResolutionPlan : null; OriginalUnaryRequest = unaryZero != null ? unaryZero.Request : null; OriginalTransferRequest = transferZero != null ? transferZero.Request : null; IntentTransformOutcomes = unaryZero != null ? unaryZero.TransformOutcomes : transferZero != null ? transferZero.TransformOutcomes : Empty<DomainLawOutcomeTrace>(); RelationalOutcomes = UnaryGenerationOne != null ? UnaryGenerationOne.RelationalOutcomes : TransferGenerationOne != null ? TransferGenerationOne.RelationalOutcomes : Empty<DomainLawOutcomeTrace>(); CatalysisObservations = two != null ? two.Observations : Empty<CatalysisObservationTrace>(); AllTransitions = BuildTransitions(unaryZero, transferZero, UnaryGenerationOne, TransferGenerationOne, two); GenerationOneCollisions = UnaryGenerationOne != null ? UnaryGenerationOne.ProposalCollisions : TransferGenerationOne != null ? TransferGenerationOne.ProposalCollisions : Empty<ProposalCollision>(); GenerationTwoCollisions = two != null ? two.ProposalCollisions : Empty<ProposalCollision>(); AllAuthoritativeTransitions = BuildAuthority(unaryZero,transferZero,resolvedOne,finalResolution); }
        public DomainResolutionPlan ResolutionPlan { get; } public UnaryDomainGenerationZeroResult UnaryGenerationZero { get; } public TransferDomainGenerationZeroResult TransferGenerationZero { get; } public DomainResolvedGenerationOneResult ResolvedGenerationOne { get; } public UnaryDomainGenerationOneResult UnaryGenerationOne { get; } public TransferDomainGenerationOneResult TransferGenerationOne { get; } public DomainGenerationTwoResult GenerationTwo { get; } public DomainProposalCompositionIntegrationResult FinalResolution { get; }
        public UnaryDomainOrchestrationRequest OriginalUnaryRequest { get; } public TransferDomainOrchestrationRequest OriginalTransferRequest { get; } public IReadOnlyList<DomainLawOutcomeTrace> IntentTransformOutcomes { get; } public IReadOnlyList<DomainLawOutcomeTrace> RelationalOutcomes { get; } public IReadOnlyList<CatalysisObservationTrace> CatalysisObservations { get; }
        public IReadOnlyList<NormalizedSemanticTransition> AllTransitions { get; } public IReadOnlyList<NormalizedSemanticTransition> AllRawTransitions => AllTransitions; public IReadOnlyList<DomainAuthoritativeTransition> AllAuthoritativeTransitions { get; } public IReadOnlyList<ProposalCollision> GenerationOneCollisions { get; } public IReadOnlyList<ProposalCollision> GenerationTwoCollisions { get; }
        public IReadOnlyList<DomainProposalCompositionResult> GenerationOneCompositionResults => FinalResolution != null ? FinalResolution.GenerationOneCompositions : Empty<DomainProposalCompositionResult>(); public IReadOnlyList<DomainProposalCompositionResult> GenerationTwoCompositionResults => FinalResolution != null ? FinalResolution.GenerationTwoCompositions : Empty<DomainProposalCompositionResult>(); public IReadOnlyList<DomainComposedTransition> ComposedGenerationOneTransitions => FinalResolution != null ? FinalResolution.GenerationOneComposedTransitions : Empty<DomainComposedTransition>(); public IReadOnlyList<DomainComposedTransition> ComposedGenerationTwoTransitions => FinalResolution != null ? FinalResolution.GenerationTwoComposedTransitions : Empty<DomainComposedTransition>(); public IReadOnlyList<DomainFinalSemanticState> FinalStates => FinalResolution != null ? FinalResolution.FinalStates : Empty<DomainFinalSemanticState>(); public IReadOnlyList<DomainUnresolvedSemanticKey> FinalUnresolvedKeys => FinalResolution != null ? FinalResolution.UnresolvedKeys : Empty<DomainUnresolvedSemanticKey>();
        public bool HasRawProposalCollisions => GenerationOneCollisions.Count + GenerationTwoCollisions.Count > 0; public bool HasUnresolvedProposalCollisions => FinalResolution != null && FinalResolution.HasUnresolvedProposalCollisions; public bool HasUnresolvedCollisions => HasUnresolvedProposalCollisions; public bool IsCausallyTerminal => true;
        public DomainOrchestrationGeneration MaximumGenerationReached => GenerationTwo != null && GenerationTwo.Transitions.Count > 0 ? DomainOrchestrationGeneration.Generation2 : UnaryGenerationOne != null ? UnaryGenerationOne.MaximumGeneration : TransferGenerationOne != null ? TransferGenerationOne.MaximumGeneration : DomainOrchestrationGeneration.Generation0;
        public bool Succeeded => GenerationTwo != null && GenerationTwo.Succeeded && FinalResolution != null && FinalResolution.Succeeded;
        private static IReadOnlyList<NormalizedSemanticTransition> BuildTransitions(UnaryDomainGenerationZeroResult uz, TransferDomainGenerationZeroResult tz, UnaryDomainGenerationOneResult u1, TransferDomainGenerationOneResult t1, DomainGenerationTwoResult two) { List<NormalizedSemanticTransition> list = new List<NormalizedSemanticTransition>(); if (uz != null && uz.PrimaryTransition != null) list.Add(uz.PrimaryTransition); if (tz != null) { if (tz.SourceTransition != null) list.Add(tz.SourceTransition); if (tz.TargetTransition != null) list.Add(tz.TargetTransition); } if (u1 != null) list.AddRange(u1.Transitions); if (t1 != null) list.AddRange(t1.Transitions); if (two != null) list.AddRange(two.Transitions); list.Sort((left, right) => left.SequenceId.CompareTo(right.SequenceId)); return list.AsReadOnly(); }
        private static IReadOnlyList<DomainAuthoritativeTransition> BuildAuthority(UnaryDomainGenerationZeroResult uz, TransferDomainGenerationZeroResult tz, DomainResolvedGenerationOneResult one, DomainProposalCompositionIntegrationResult final) { List<DomainAuthoritativeTransition> list=new List<DomainAuthoritativeTransition>();if(uz!=null&&uz.PrimaryTransition!=null)list.Add(new DomainAuthoritativeTransition(uz.PrimaryTransition));if(tz!=null){if(tz.SourceTransition!=null)list.Add(new DomainAuthoritativeTransition(tz.SourceTransition));if(tz.TargetTransition!=null)list.Add(new DomainAuthoritativeTransition(tz.TargetTransition));}if(one!=null)for(int i=0;i<one.AuthoritativeTransitions.Count;i++)list.Add(new DomainAuthoritativeTransition(one.AuthoritativeTransitions[i]));if(final!=null)for(int i=0;i<final.AuthoritativeGenerationTwoTransitions.Count;i++)list.Add(final.AuthoritativeGenerationTwoTransitions[i]);list.Sort((left,right)=>left.SequenceId.CompareTo(right.SequenceId));return list.AsReadOnly(); }
        private static IReadOnlyList<T> Empty<T>() { return new List<T>().AsReadOnly(); }
    }

    public static class DomainGenerationTwoExecutor
    {
        public static DomainGenerationTwoResult Execute(DomainResolvedGenerationOneResult resolved)
        {
            if (!IsValid(resolved))
                return new DomainGenerationTwoResult(resolved, Empty<CatalysisObservationTrace>(), Empty<CatalysisEvaluationResult>(), Empty<NormalizedSemanticTransition>(), Empty<ProposalCollision>(), DomainGenerationTwoRejectionReason.ResolvedGenerationOneRequired);
            DomainResolutionPlan plan = resolved.ResolutionPlan;
            List<ObserverSource> history = Sources(resolved);
            List<CatalysisObservationTrace> observations = new List<CatalysisObservationTrace>(); List<CatalysisEvaluationResult> evaluations = new List<CatalysisEvaluationResult>(); List<BranchTransition> proposed = new List<BranchTransition>();
            int nextId = resolved.NextTransitionId.Value;
            for (int transitionIndex = 0; transitionIndex < history.Count; transitionIndex++)
            {
                ObserverSource sourceTransition = history[transitionIndex];
                for (int lawIndex = 0; lawIndex < plan.Laws.Count; lawIndex++)
                {
                    PlannedDomainLaw planned = plan.Laws[lawIndex];
                    if (planned.Phase != DomainResolutionCausalPhase.PostResolutionObservation || !planned.SharedEligible || planned.CandidateLaw.Phenomenon != sourceTransition.Phenomenon) continue;
                    if (IsUnresolved(resolved, sourceTransition.CarrierId, sourceTransition.Phenomenon)) { observations.Add(Trace(planned.CandidateLaw, sourceTransition, false, false, false, null, CatalysisObservationBlockReason.SourceStateUnresolved, 0, Empty<CatalysisRecipientObservationBlock>())); continue; }
                    DomainOrchestrationContextSet contexts = Contexts(resolved);
                    CatalysisOrchestrationContext context;
                    if (contexts == null || !contexts.TryGetCatalysisForSource(planned.CandidateLaw, sourceTransition.CarrierId, out context)) { observations.Add(Trace(planned.CandidateLaw, sourceTransition, false, false, false, null, CatalysisObservationBlockReason.ContextUnavailable, 0, Empty<CatalysisRecipientObservationBlock>())); continue; }
                    List<CatalysisRecipientObservationBlock> blocks = new List<CatalysisRecipientObservationBlock>();
                    PhenomenonCarrierTopology topology = AdaptTopology(context.Topology, sourceTransition, resolved, blocks);
                    CatalysisEvaluationResult evaluation = CatalysisEvaluator.Evaluate(new CatalysisEvaluationRequest(planned.CandidateLaw, ExpressionContext(resolved), topology, sourceTransition.Before, sourceTransition.After));
                    evaluations.Add(evaluation);
                    int start = proposed.Count;
                    if (evaluation.Succeeded)
                        for (int recipientIndex = 0; recipientIndex < evaluation.RecipientResults.Count; recipientIndex++)
                        { CatalysisRecipientResult recipient = evaluation.RecipientResults[recipientIndex]; if (recipient.Succeeded) proposed.Add(new BranchTransition(new CatalysisObserverBranchKey(planned.CandidateLaw, sourceTransition.SequenceId), new NormalizedSemanticTransition(new DomainTransitionSequenceId(nextId++), DomainOrchestrationGeneration.Generation2, sourceTransition.SequenceId, recipient.CarrierId, sourceTransition.Phenomenon, recipient.Before, recipient.After, recipient.GeneratedOperation, recipient.GeneratedMagnitude, DomainTransitionOrigin.Catalysis, planned.CandidateLaw, true))); }
                    observations.Add(Trace(planned.CandidateLaw, sourceTransition, true, true, evaluation.TriggerDetected, evaluation.Succeeded ? (CatalysisEvaluationRejectionReason?)null : evaluation.RejectionReason, evaluation.Succeeded ? CatalysisObservationBlockReason.None : CatalysisObservationBlockReason.EvaluatorRejected, proposed.Count - start, blocks.AsReadOnly()));
                }
            }
            List<ProposalCollision> collisions; IReadOnlyList<NormalizedSemanticTransition> finalTransitions = DetectCollisions(proposed, out collisions);
            return new DomainGenerationTwoResult(resolved, observations.AsReadOnly(), evaluations.AsReadOnly(), finalTransitions, collisions.AsReadOnly(), DomainGenerationTwoRejectionReason.None);
        }
        private static PhenomenonCarrierTopology AdaptTopology(PhenomenonCarrierTopology supplied, ObserverSource source, DomainResolvedGenerationOneResult resolved, List<CatalysisRecipientObservationBlock> blocks)
        { List<PhenomenonCarrierSnapshot> recipients = new List<PhenomenonCarrierSnapshot>(); if (supplied != null) for (int index = 0; index < supplied.OrderedRecipients.Count; index++) { PhenomenonCarrierSnapshot recipient = supplied.OrderedRecipients[index]; if (recipient == null) { recipients.Add(null); continue; } DomainPostGenerationOneState state; if (resolved.TryGetPostGenerationOneState(recipient.CarrierId, source.Phenomenon, out state)) { if (state.IsUnresolved || state.Snapshot == null) { blocks.Add(new CatalysisRecipientObservationBlock(recipient.CarrierId)); continue; } recipients.Add(new PhenomenonCarrierSnapshot(recipient.CarrierId, recipient.Phenomenon, state.Snapshot)); } else recipients.Add(recipient); } return new PhenomenonCarrierTopology(new PhenomenonCarrierSnapshot(source.CarrierId, source.Phenomenon, source.Before), recipients); }
        private static IReadOnlyList<NormalizedSemanticTransition> DetectCollisions(IReadOnlyList<BranchTransition> proposed, out List<ProposalCollision> collisions)
        { collisions = new List<ProposalCollision>(); bool[] collided = new bool[proposed.Count]; for (int index = 0; index < proposed.Count; index++) { List<int> matches = new List<int>(); List<CatalysisObserverBranchKey> branches = new List<CatalysisObserverBranchKey>(); List<DomainLaw> laws = new List<DomainLaw>(); for (int candidate = 0; candidate < proposed.Count; candidate++) if (proposed[candidate].Transition.CarrierId.Equals(proposed[index].Transition.CarrierId) && proposed[candidate].Transition.Phenomenon == proposed[index].Transition.Phenomenon) { matches.Add(candidate); if (!Contains(branches, proposed[candidate].Branch)) branches.Add(proposed[candidate].Branch); if (!laws.Contains(proposed[candidate].Transition.OriginatingLaw)) laws.Add(proposed[candidate].Transition.OriginatingLaw); } if (branches.Count < 2) continue; bool seen = false; for (int c = 0; c < collisions.Count; c++) if (collisions[c].CarrierId.Equals(proposed[index].Transition.CarrierId) && collisions[c].Phenomenon == proposed[index].Transition.Phenomenon) seen = true; if (seen) continue; List<DomainTransitionSequenceId> ids = new List<DomainTransitionSequenceId>(); for (int m = 0; m < matches.Count; m++) { collided[matches[m]] = true; ids.Add(proposed[matches[m]].Transition.SequenceId); } collisions.Add(new ProposalCollision(proposed[index].Transition.CarrierId, proposed[index].Transition.Phenomenon, DomainOrchestrationGeneration.Generation2, ids, laws)); } List<NormalizedSemanticTransition> final = new List<NormalizedSemanticTransition>(); for (int i = 0; i < proposed.Count; i++) final.Add(collided[i] ? proposed[i].Transition.WithUnambiguous(false) : proposed[i].Transition); return final.AsReadOnly(); }
        private static bool Contains(IReadOnlyList<CatalysisObserverBranchKey> values, CatalysisObserverBranchKey key) { for (int i = 0; i < values.Count; i++) if (values[i].Equals(key)) return true; return false; }
        private static List<ObserverSource> Sources(DomainResolvedGenerationOneResult resolved) { List<ObserverSource> history = new List<ObserverSource>(); if (resolved.UnaryRaw != null) history.Add(new ObserverSource(resolved.UnaryRaw.GenerationZero.PrimaryTransition)); else { history.Add(new ObserverSource(resolved.TransferRaw.GenerationZero.SourceTransition)); history.Add(new ObserverSource(resolved.TransferRaw.GenerationZero.TargetTransition)); } for (int i = 0; i < resolved.AuthoritativeTransitions.Count; i++) history.Add(new ObserverSource(resolved.AuthoritativeTransitions[i])); history.Sort((left, right) => left.SequenceId.CompareTo(right.SequenceId)); return history; }
        private static bool IsUnresolved(DomainResolvedGenerationOneResult resolved, PhenomenonCarrierId id, LawPhenomenon phenomenon) { DomainPostGenerationOneState state; return resolved.TryGetPostGenerationOneState(id, phenomenon, out state) && state.IsUnresolved; }
        private static DomainOrchestrationContextSet Contexts(DomainResolvedGenerationOneResult resolved) { return resolved.UnaryRaw != null ? resolved.UnaryRaw.GenerationZero.Request.Contexts : resolved.TransferRaw.GenerationZero.Request.Contexts; }
        private static LawExpressionContext ExpressionContext(DomainResolvedGenerationOneResult resolved) { return resolved.UnaryRaw != null ? resolved.UnaryRaw.GenerationZero.Request.ExpressionContext : resolved.TransferRaw.GenerationZero.Request.ExpressionContext; }
        private static bool IsValid(DomainResolvedGenerationOneResult resolved) { return resolved != null && resolved.Succeeded && resolved.NextTransitionId.IsValid && resolved.ResolutionPlan != null && resolved.AuthoritativeTransitions != null && resolved.PostGenerationOneStates != null && resolved.UnresolvedKeys != null && ValidAuthority(resolved.AuthoritativeTransitions) && NoNulls(resolved.PostGenerationOneStates) && NoNulls(resolved.UnresolvedKeys) && ((resolved.UnaryRaw != null && resolved.TransferRaw == null && resolved.UnaryRaw.Succeeded && resolved.UnaryRaw.GenerationZero != null && resolved.UnaryRaw.GenerationZero.Succeeded && resolved.UnaryRaw.GenerationZero.PrimaryTransition != null) || (resolved.TransferRaw != null && resolved.UnaryRaw == null && resolved.TransferRaw.Succeeded && resolved.TransferRaw.GenerationZero != null && resolved.TransferRaw.GenerationZero.Succeeded && resolved.TransferRaw.GenerationZero.SourceTransition != null && resolved.TransferRaw.GenerationZero.TargetTransition != null)); }
        private static bool ValidAuthority(IReadOnlyList<DomainAuthoritativeGenerationOneTransition> values) { for (int i = 0; i < values.Count; i++) if (values[i] == null || !values[i].SequenceId.IsValid || values[i].Before == null || values[i].After == null) return false; return true; }
        private static bool NoNulls<T>(IReadOnlyList<T> values) where T : class { for (int i = 0; i < values.Count; i++) if (values[i] == null) return false; return true; }
        private static CatalysisObservationTrace Trace(DomainLaw law, ObserverSource source, bool attempted, bool context, bool triggered, CatalysisEvaluationRejectionReason? rejection, CatalysisObservationBlockReason block, int count, IReadOnlyList<CatalysisRecipientObservationBlock> recipientBlocks) { return new CatalysisObservationTrace(law, source.SequenceId, source.CarrierId, attempted, context, triggered, rejection, block, count, recipientBlocks); }
        private static IReadOnlyList<T> Empty<T>() { return new List<T>().AsReadOnly(); }
        private sealed class ObserverSource { public ObserverSource(NormalizedSemanticTransition transition) { SequenceId=transition.SequenceId; CarrierId=transition.CarrierId; Phenomenon=transition.Phenomenon; Before=transition.Before; After=transition.After; } public ObserverSource(DomainAuthoritativeGenerationOneTransition transition) { SequenceId=transition.SequenceId; CarrierId=transition.CarrierId; Phenomenon=transition.Phenomenon; Before=transition.Before; After=transition.After; } public DomainTransitionSequenceId SequenceId; public PhenomenonCarrierId CarrierId; public LawPhenomenon Phenomenon; public PhenomenonSemanticSnapshot Before; public PhenomenonSemanticSnapshot After; }
        private sealed class BranchTransition { public BranchTransition(CatalysisObserverBranchKey branch, NormalizedSemanticTransition transition) { Branch = branch; Transition = transition; } public CatalysisObserverBranchKey Branch; public NormalizedSemanticTransition Transition; }
    }
    public static class DomainBoundedOrchestrator
    {
        public static DomainBoundedOrchestrationResult Execute(UnaryDomainOrchestrationRequest request) { UnaryDomainGenerationZeroResult zero = DomainGenerationZeroExecutor.Execute(request); UnaryDomainGenerationOneResult one = DomainGenerationOneExecutor.Execute(zero); DomainResolvedGenerationOneResult resolved = DomainResolvedGenerationOneBuilder.Resolve(one); DomainGenerationTwoResult two = DomainGenerationTwoExecutor.Execute(resolved); DomainProposalCompositionIntegrationResult final = DomainProposalCompositionIntegrator.ResolveGenerationTwo(two); return new DomainBoundedOrchestrationResult(zero, null, resolved, two, final); }
        public static DomainBoundedOrchestrationResult Execute(TransferDomainOrchestrationRequest request) { TransferDomainGenerationZeroResult zero = DomainGenerationZeroExecutor.Execute(request); TransferDomainGenerationOneResult one = DomainGenerationOneExecutor.Execute(zero); DomainResolvedGenerationOneResult resolved = DomainResolvedGenerationOneBuilder.Resolve(one); DomainGenerationTwoResult two = DomainGenerationTwoExecutor.Execute(resolved); DomainProposalCompositionIntegrationResult final = DomainProposalCompositionIntegrator.ResolveGenerationTwo(two); return new DomainBoundedOrchestrationResult(null, zero, resolved, two, final); }
    }
}
