using System.Collections.Generic;

namespace Cave.Domain
{
    /// <summary>Deterministic, scene-free coverage of the locked cross-Domain pipeline.</summary>
    public static class DomainConflictArbitrationVerification
    {
        public static bool TryRunAll(out string failure)
        {
            DomainConflictContestKey heat = Key("A", LawPhenomenon.Heat); DomainConflictContestKey mass = Key("A", LawPhenomenon.Mass);
            CrossDomainArbitrationResult one = DomainConflictArbitrator.Arbitrate(Read(Participant("A", Plan(Entry("A",LawPhenomenon.Heat,0f,2f)), EmptyEvidence(), DomainComposition.Empty)));
            CrossDomainArbitrationResult differentKeys = DomainConflictArbitrator.Arbitrate(Read(Participant("A",Plan(Entry("A",LawPhenomenon.Heat,0f,2f)),EmptyEvidence(),DomainComposition.Empty),Participant("B",Plan(Entry("A",LawPhenomenon.Mass,0f,2f)),EmptyEvidence(),DomainComposition.Empty)));
            CrossDomainArbitrationResult consensus = DomainConflictArbitrator.Arbitrate(Read(Participant("A",Plan(Entry("A",LawPhenomenon.Heat,0f,2f)),EmptyEvidence(),DomainComposition.Empty),Participant("B",Plan(Entry("A",LawPhenomenon.Heat,0f,2f)),EmptyEvidence(),DomainComposition.Empty)));
            CrossDomainArbitrationResult jurisdiction = DomainConflictArbitrator.Arbitrate(Read(Participant("A",Plan(Entry("A",LawPhenomenon.Heat,0f,0f)),Evidence("A",heat,true,0,0),DomainComposition.Empty),Participant("B",Plan(Entry("A",LawPhenomenon.Heat,0f,2f)),Evidence("B",heat,false,99,99),DomainComposition.Empty)));
            CrossDomainArbitrationResult mismatch = DomainConflictArbitrator.Arbitrate(Read(Participant("A",Plan(Entry("A",LawPhenomenon.Heat,0f,2f)),EmptyEvidence(),DomainComposition.Empty),Participant("B",Plan(Entry("A",LawPhenomenon.Heat,1f,-2f)),EmptyEvidence(),DomainComposition.Empty)));
            CrossDomainArbitrationResult none = DomainConflictArbitrator.Arbitrate(Read(Participant("A",Plan(Entry("A",LawPhenomenon.Heat,0f,2f)),Evidence("A",heat,false,0,0),DomainComposition.Empty),Participant("B",Plan(Entry("A",LawPhenomenon.Heat,0f,-2f)),Evidence("B",heat,false,0,0),DomainComposition.Empty)));
            CrossDomainArbitrationResult specificity = DomainConflictArbitrator.Arbitrate(Read(Participant("A",Plan(Entry("A",LawPhenomenon.Heat,0f,2f)),Evidence("A",heat,true,3,0),DomainComposition.Empty),Participant("B",Plan(Entry("A",LawPhenomenon.Heat,0f,-2f)),Evidence("B",heat,true,2,100),LargeComposition())));
            CrossDomainArbitrationResult authority = DomainConflictArbitrator.Arbitrate(Read(Participant("A",Plan(Entry("A",LawPhenomenon.Heat,0f,2f)),Evidence("A",heat,true,2,1),LargeComposition()),Participant("B",Plan(Entry("A",LawPhenomenon.Heat,0f,-2f)),Evidence("B",heat,true,2,4),DomainComposition.Empty)));
            CrossDomainArbitrationResult complexity = DomainConflictArbitrator.Arbitrate(Read(Participant("A",Plan(Entry("A",LawPhenomenon.Heat,0f,2f)),Evidence("A",heat,true,2,4),LargeComposition()),Participant("B",Plan(Entry("A",LawPhenomenon.Heat,0f,-2f)),Evidence("B",heat,true,2,4),DomainComposition.Empty)));
            CrossDomainArbitrationResult stalemate = DomainConflictArbitrator.Arbitrate(Read(Participant("A",Plan(Entry("A",LawPhenomenon.Heat,0f,2f)),Evidence("A",heat,true,2,4),DomainComposition.Empty),Participant("B",Plan(Entry("A",LawPhenomenon.Heat,0f,-2f)),Evidence("B",heat,true,2,4),DomainComposition.Empty)));
            CrossDomainArbitrationResult missingSpecificity = DomainConflictArbitrator.Arbitrate(Read(Participant("A",Plan(Entry("A",LawPhenomenon.Heat,0f,2f)),JurisdictionOnly("A",heat,true),DomainComposition.Empty),Participant("B",Plan(Entry("A",LawPhenomenon.Heat,0f,-2f)),JurisdictionOnly("B",heat,true),DomainComposition.Empty)));
            CrossDomainArbitrationResult perKey = DomainConflictArbitrator.Arbitrate(Read(Participant("A",Plan(Entry("A",LawPhenomenon.Heat,0f,2f),Entry("A",LawPhenomenon.Mass,0f,-2f)),EvidenceMany("A",heat,true,3,0,mass,true,1,0),DomainComposition.Empty),Participant("B",Plan(Entry("A",LawPhenomenon.Heat,0f,-2f),Entry("A",LawPhenomenon.Mass,0f,2f)),EvidenceMany("B",heat,true,2,0,mass,true,4,0),DomainComposition.Empty)));
            DomainCommitPlan invalidPlan = new DomainCommitPlan(null, Read(Entry("Z",LawPhenomenon.Heat,0f,1f)), DomainCommitPlanRejectionReason.None);
            CrossDomainArbitrationResult invalidParticipant = DomainConflictArbitrator.Arbitrate(Read(new DomainConflictParticipant("invalid",invalidPlan,DomainComposition.Empty,null,DomainConflictEvidenceSet.Empty,"test")));

            bool pass = one.Succeeded && one.Outcomes.Count==1 && one.Outcomes[0].Kind==DomainConflictOutcomeKind.Uncontested && one.AuthoritativeWrites.Count==1
                && differentKeys.Succeeded && differentKeys.Outcomes.Count==2 && differentKeys.AuthoritativeWrites.Count==2
                && consensus.Succeeded && consensus.Outcomes[0].Kind==DomainConflictOutcomeKind.Consensus && consensus.AuthoritativeWrites.Count==1 && consensus.AuthoritativeWrites[0].SupportingParticipantIds.Count==2
                && jurisdiction.Succeeded && jurisdiction.Outcomes[0].Kind==DomainConflictOutcomeKind.SelectedByJurisdiction && jurisdiction.Outcomes[0].SelectedCandidate.ParticipantId=="A" && jurisdiction.Outcomes[0].Trace!=null && !jurisdiction.Outcomes[0].Trace.SpecificityRequired
                && !mismatch.Succeeded && mismatch.HasActualConflicts && mismatch.HasInvalidConflicts && mismatch.Outcomes[0].Kind==DomainConflictOutcomeKind.InvalidBaselineMismatch && mismatch.AuthoritativeWrites.Count==0
                && none.Succeeded && none.HasBaselineDeferrals && none.Outcomes[0].Kind==DomainConflictOutcomeKind.BaselineDeferredNoJurisdiction && none.AuthoritativeWrites.Count==0
                && specificity.Succeeded && specificity.Outcomes[0].Kind==DomainConflictOutcomeKind.SelectedBySpecificity && specificity.Outcomes[0].SelectedCandidate.ParticipantId=="A"
                && authority.Succeeded && authority.Outcomes[0].Kind==DomainConflictOutcomeKind.SelectedByAuthority && authority.Outcomes[0].SelectedCandidate.ParticipantId=="B"
                && complexity.Succeeded && complexity.Outcomes[0].Kind==DomainConflictOutcomeKind.SelectedByCommittedComplexity && complexity.Outcomes[0].SelectedCandidate.ParticipantId=="A"
                && stalemate.Succeeded && stalemate.Outcomes[0].Kind==DomainConflictOutcomeKind.BaselineDeferredStalemate && stalemate.AuthoritativeWrites.Count==0
                && !missingSpecificity.Succeeded && missingSpecificity.Outcomes[0].Kind==DomainConflictOutcomeKind.InvalidEvidence
                && perKey.Succeeded && perKey.Outcomes.Count==2 && perKey.Outcomes[0].SelectedCandidate.ParticipantId=="A" && perKey.Outcomes[1].SelectedCandidate.ParticipantId=="B"
                && invalidParticipant.RejectionReason==CrossDomainArbitrationRejectionReason.InvalidParticipant;
            failure=pass?null:"Cross-Domain arbitration verification failed.";return pass;
        }
        private static DomainConflictParticipant Participant(string id,DomainCommitPlan plan,DomainConflictEvidenceSet evidence,DomainComposition composition){return new DomainConflictParticipant(id,plan,composition,null,evidence,"test");}
        private static DomainConflictEvidenceSet EmptyEvidence(){return DomainConflictEvidenceSet.Empty;}
        private static DomainConflictEvidenceSet JurisdictionOnly(string id,DomainConflictContestKey key,bool jurisdiction){return new DomainConflictEvidenceSet(Read(new DomainJurisdictionEvidence(id,key,jurisdiction,"test")),null,null);}
        private static DomainConflictEvidenceSet Evidence(string id,DomainConflictContestKey key,bool jurisdiction,int specificity,int authority){return EvidenceMany(id,key,jurisdiction,specificity,authority,default(DomainConflictContestKey),false,0,0);}
        private static DomainConflictEvidenceSet EvidenceMany(string id,DomainConflictContestKey first,bool firstJurisdiction,int firstSpecificity,int firstAuthority,DomainConflictContestKey second,bool secondJurisdiction,int secondSpecificity,int secondAuthority){List<DomainJurisdictionEvidence> jurisdiction=new List<DomainJurisdictionEvidence>{new DomainJurisdictionEvidence(id,first,firstJurisdiction,"test")};List<DomainSpecificityEvidence> specificity=new List<DomainSpecificityEvidence>{new DomainSpecificityEvidence(id,first,firstSpecificity,"test")};List<DomainConflictAuthorityEvidence> authority=new List<DomainConflictAuthorityEvidence>{new DomainConflictAuthorityEvidence(id,first,firstAuthority,"test")};if(!second.Equals(default(DomainConflictContestKey))){jurisdiction.Add(new DomainJurisdictionEvidence(id,second,secondJurisdiction,"test"));specificity.Add(new DomainSpecificityEvidence(id,second,secondSpecificity,"test"));authority.Add(new DomainConflictAuthorityEvidence(id,second,secondAuthority,"test"));}return new DomainConflictEvidenceSet(jurisdiction,specificity,authority);}
        private static DomainConflictContestKey Key(string carrier,LawPhenomenon phenomenon){return new DomainConflictContestKey(new PhenomenonCarrierId(carrier),phenomenon);}
        private static DomainComposition LargeComposition(){DomainLaw first;DomainLaw second;LawValidationResult result;DomainLaw.TryCreate(LawExpression.Projectile,LawPhenomenon.Heat,LawTerritoryPrinciple.Propagation,out first,out result);DomainLaw.TryCreate(LawExpression.Projectile,LawPhenomenon.Flow,LawTerritoryPrinciple.Catalysis,out second,out result);return DomainCompositionEditor.Add(DomainCompositionEditor.Add(DomainComposition.Empty,first).Resulting,second).Resulting;}
        private static DomainCommitEntry Entry(string carrier,LawPhenomenon phenomenon,float before,float after){return new DomainCommitEntry(new PhenomenonCarrierId(carrier),phenomenon,Snapshot(phenomenon,before),Snapshot(phenomenon,after),Read(new DomainTransitionSequenceId(1)));}
        private static DomainCommitPlan Plan(params DomainCommitEntry[] entries){List<NormalizedSemanticTransition> g2=new List<NormalizedSemanticTransition>();for(int i=0;i<entries.Length;i++)g2.Add(new NormalizedSemanticTransition(new DomainTransitionSequenceId(i+1),DomainOrchestrationGeneration.Generation2,new DomainTransitionSequenceId(0),entries[i].CarrierId,entries[i].Phenomenon,entries[i].ExpectedBefore,entries[i].FinalAfter,PhenomenonOperationKind.Add,1f,DomainTransitionOrigin.Catalysis,null,true));return DomainCommitPlanBuilder.Build(Bounded(g2.AsReadOnly()));}
        private static DomainBoundedOrchestrationResult Bounded(IReadOnlyList<NormalizedSemanticTransition> g2){NormalizedSemanticTransition seed=g2[0];UnaryDomainGenerationZeroResult zero=DomainGenerationZeroExecutor.Execute(new UnaryDomainOrchestrationRequest(DomainComposition.Empty,new LawExpressionContext(true,LawExpression.Projectile,false),seed.Phenomenon,PhenomenonOperationKind.Add,1f,new PhenomenonCarrierSnapshot(seed.CarrierId,seed.Phenomenon,seed.Before),DomainOrchestrationContextSet.Empty));UnaryDomainGenerationOneResult one=new UnaryDomainGenerationOneResult(zero,Empty<DomainLawOutcomeTrace>(),Empty<PropagationEvaluationResult>(),Empty<SynchronizationEvaluationResult>(),Empty<NormalizedSemanticTransition>(),Empty<ProposalCollision>(),DomainGenerationOneRejectionReason.None);DomainResolvedGenerationOneResult resolved=DomainResolvedGenerationOneBuilder.Resolve(one);DomainGenerationTwoResult two=new DomainGenerationTwoResult(resolved,Empty<CatalysisObservationTrace>(),Empty<CatalysisEvaluationResult>(),g2,Empty<ProposalCollision>(),DomainGenerationTwoRejectionReason.None);return new DomainBoundedOrchestrationResult(zero,null,resolved,two,DomainProposalCompositionIntegrator.ResolveGenerationTwo(two));}
        private static PhenomenonSemanticSnapshot Snapshot(LawPhenomenon phenomenon,float value){PhenomenonSemanticSnapshot snapshot;PhenomenonSemanticResult result;PhenomenonSemanticClassifier.TryCreateSnapshot(phenomenon,value,out snapshot,out result);return snapshot;}
        private static IReadOnlyList<T> Read<T>(params T[] values){return new List<T>(values).AsReadOnly();}private static IReadOnlyList<T> Empty<T>(){return new List<T>().AsReadOnly();}
    }
}
